package agentrefs

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

func ComputeSHA256(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", sha256.Sum256(data)), nil
}

func sortDocument(doc *ReferenceDocument) {
	sort.Slice(doc.SourceInputs, func(i, j int) bool {
		if doc.SourceInputs[i].Path != doc.SourceInputs[j].Path {
			return doc.SourceInputs[i].Path < doc.SourceInputs[j].Path
		}
		return doc.SourceInputs[i].Role < doc.SourceInputs[j].Role
	})
	labelRank := make(map[FactLabel]int)
	for i, l := range FactLabelOrder {
		labelRank[l] = i
	}
	sort.Slice(doc.FactLabels, func(i, j int) bool {
		return labelRank[doc.FactLabels[i]] < labelRank[doc.FactLabels[j]]
	})
	sort.Slice(doc.Facts, func(i, j int) bool {
		return doc.Facts[i].ID < doc.Facts[j].ID
	})
	sort.Slice(doc.References, func(i, j int) bool {
		return doc.References[i].ID < doc.References[j].ID
	})
}

func RenderJSON(doc *ReferenceDocument) ([]byte, error) {
	sortDocument(doc)
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func RenderMarkdown(doc *ReferenceDocument) ([]byte, error) {
	sortDocument(doc)
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s\n\n", doc.ReferenceID))
	b.WriteString(fmt.Sprintf("Schema version: `%s`\n\n", doc.SchemaVersion))

	b.WriteString("## Repo\n\n")
	b.WriteString(fmt.Sprintf("- Project: `%s`\n", doc.Repo.ProjectID))
	b.WriteString(fmt.Sprintf("- Repo: `%s`\n", doc.Repo.RepoID))
	b.WriteString(fmt.Sprintf("- Branch: `%s`\n\n", doc.Repo.Branch))

	b.WriteString("## Generated By\n\n")
	b.WriteString(fmt.Sprintf("- Name: `%s`\n", doc.GeneratedBy.Name))
	b.WriteString(fmt.Sprintf("- Version: `%s`\n\n", doc.GeneratedBy.Version))

	b.WriteString("## Rendering Contract\n\n")
	b.WriteString(fmt.Sprintf("- JSON primary: `%v`\n", doc.Rendering.JSONPrimary))
	b.WriteString(fmt.Sprintf("- Markdown from JSON: `%v`\n", doc.Rendering.MarkdownFromJSON))
	b.WriteString(fmt.Sprintf("- Deterministic sort: `%v`\n", doc.Rendering.DeterministicSort))
	b.WriteString(fmt.Sprintf("- No timestamps: `%v`\n", doc.Rendering.NoTimestamps))
	b.WriteString(fmt.Sprintf("- Relative paths only: `%v`\n\n", doc.Rendering.RelativePathsOnly))

	if len(doc.SourceInputs) > 0 {
		b.WriteString("## Source Inputs\n\n")
		b.WriteString("| Path | SHA256 | Role |\n")
		b.WriteString("| --- | --- | --- |\n")
		for _, si := range doc.SourceInputs {
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", si.Path, si.SHA256, si.Role))
		}
		b.WriteString("\n")
	}

	if len(doc.FactLabels) > 0 {
		b.WriteString("## Fact Labels\n\n")
		for _, fl := range doc.FactLabels {
			b.WriteString(fmt.Sprintf("- `%s`\n", fl))
		}
		b.WriteString("\n")
	}

	if len(doc.Facts) > 0 {
		b.WriteString("## Facts\n\n")
		for _, f := range doc.Facts {
			b.WriteString(fmt.Sprintf("### %s (%s)\n\n", f.ID, f.Label))
			b.WriteString(fmt.Sprintf("%s\n\n", f.Statement))
			if len(f.Evidence) > 0 {
				b.WriteString("Evidence:\n\n")
				for _, e := range f.Evidence {
					b.WriteString(fmt.Sprintf("- %s: `%s`\n", e.Kind, e.Value))
				}
				b.WriteString("\n")
			}
		}
	}

	if len(doc.References) > 0 {
		b.WriteString("## References\n\n")
		b.WriteString("| ID | Kind | Path | Description |\n")
		b.WriteString("| --- | --- | --- | --- |\n")
		for _, r := range doc.References {
			b.WriteString(fmt.Sprintf("| `%s` | %s | `%s` | %s |\n", r.ID, r.Kind, r.Path, r.Description))
		}
		b.WriteString("\n")
	}

	return []byte(b.String()), nil
}
