import { asWorkflowRecord, malformedWorkflowResponse, requestWorkflowJson, requestWorkflowText, requiredWorkflowArray, requiredWorkflowInteger, requiredWorkflowString, type WorkflowHttpMethod, type WorkflowJsonRecord } from "@/features/workflow-api";
import type { ProgramDispatch, ProgramHandoff, ProgramHandoffMember, ProgramHandoffResult, ProgramMember } from "./types";
const record = (value: unknown, method: WorkflowHttpMethod, path: string, context: string): WorkflowJsonRecord => asWorkflowRecord(value, method, path, context);
function member(value: unknown, method: WorkflowHttpMethod, path: string): ProgramMember { const x = record(value, method, path, "program member"); return { id: requiredWorkflowString(x, "ID", method, path, "program member"), packageId: requiredWorkflowString(x, "PackageID", method, path, "program member"), runId: requiredWorkflowString(x, "RunID", method, path, "program member"), assignmentArtifactId: requiredWorkflowString(x, "AssignmentArtifactID", method, path, "program member"), repoTarget: requiredWorkflowString(x, "RepoTarget", method, path, "program member"), branch: requiredWorkflowString(x, "Branch", method, path, "program member"), baseCommit: requiredWorkflowString(x, "BaseCommit", method, path, "program member"), state: requiredWorkflowString(x, "State", method, path, "program member"), ticketRevisionRowId: requiredWorkflowInteger(x, "TicketRevisionRowID", method, path, "program member", 1), outcome: typeof x.Outcome === "string" ? x.Outcome : "", resultBranch: typeof x.ResultBranch === "string" ? x.ResultBranch : "", branchHeadSha: typeof x.BranchHeadSHA === "string" ? x.BranchHeadSHA : "", blocker: typeof x.Blocker === "string" ? x.Blocker : "" }; }
function dispatch(value: unknown, method: WorkflowHttpMethod, path: string): ProgramDispatch { const x = record(value, method, path, "program dispatch"); return { id: requiredWorkflowString(x, "ID", method, path, "program dispatch"), workspaceId: requiredWorkflowString(x, "WorkspaceID", method, path, "program dispatch"), repoTarget: requiredWorkflowString(x, "RepoTarget", method, path, "program dispatch"), branch: requiredWorkflowString(x, "Branch", method, path, "program dispatch"), baseCommit: requiredWorkflowString(x, "BaseCommit", method, path, "program dispatch"), status: requiredWorkflowString(x, "Status", method, path, "program dispatch"), laterIntegrationRisks: typeof x.LaterIntegrationRisks === "string" ? x.LaterIntegrationRisks : "", members: requiredWorkflowArray(x, "Members", method, path, "program dispatch").map((v) => member(v, method, path)) }; }
function handoffMember(value: unknown, method: WorkflowHttpMethod, path: string): ProgramHandoffMember { const x = record(value, method, path, "program handoff member"); const assignment = x.Assignment; if (assignment === undefined || assignment === null) return malformedWorkflowResponse(method, path, "program handoff member.Assignment must be the embedded execution assignment content"); return { sequence: requiredWorkflowInteger(x, "Sequence", method, path, "program handoff member", 1), memberId: requiredWorkflowString(x, "MemberID", method, path, "program handoff member"), ticketId: requiredWorkflowString(x, "TicketID", method, path, "program handoff member"), ticketRevision: requiredWorkflowInteger(x, "TicketRevision", method, path, "program handoff member", 1), packageId: requiredWorkflowString(x, "PackageID", method, path, "program handoff member"), runId: requiredWorkflowString(x, "RunID", method, path, "program handoff member"), assignmentArtifactId: requiredWorkflowString(x, "AssignmentArtifactID", method, path, "program handoff member"), assignmentSha256: requiredWorkflowString(x, "AssignmentSHA256", method, path, "program handoff member"), assignment, repoTarget: requiredWorkflowString(x, "RepoTarget", method, path, "program handoff member"), branch: requiredWorkflowString(x, "Branch", method, path, "program handoff member"), baseCommit: requiredWorkflowString(x, "BaseCommit", method, path, "program handoff member") }; }
function handoff(value: unknown, method: WorkflowHttpMethod, path: string): ProgramHandoff { const x = record(value, method, path, "program handoff"); return { dispatchId: requiredWorkflowString(x, "DispatchID", method, path, "program handoff"), workspaceId: requiredWorkflowString(x, "WorkspaceID", method, path, "program handoff"), repoTarget: requiredWorkflowString(x, "RepoTarget", method, path, "program handoff"), branch: requiredWorkflowString(x, "Branch", method, path, "program handoff"), baseCommit: requiredWorkflowString(x, "BaseCommit", method, path, "program handoff"), members: requiredWorkflowArray(x, "Members", method, path, "program handoff").map((v) => handoffMember(v, method, path)) }; }
const base = (workspaceId: string) => `/api/feature-workspaces/${encodeURIComponent(workspaceId)}`;
export async function listProgramMembers(workspaceId: string) { const path = `${base(workspaceId)}/program-members`; const value = await requestWorkflowJson<unknown>("GET", path); if (!Array.isArray(value)) throw new Error("Malformed program members response"); return value.map((v) => member(v, "GET", path)); }
export async function prepareProgramMember(workspaceId: string, request: { packageId: string; expectedVersion: number }) { const path = `${base(workspaceId)}/program-members`; return member(await requestWorkflowJson<unknown>("POST", path, request), "POST", path); }
export async function cancelProgramMember(workspaceId: string, memberId: string, expectedVersion: number) { await requestWorkflowJson<unknown>("POST", `${base(workspaceId)}/program-members/${encodeURIComponent(memberId)}/cancel`, { expectedVersion }); }
export async function createProgramDispatch(workspaceId: string, request: { expectedVersion: number; memberIds: string[] }) { const path = `${base(workspaceId)}/program-dispatches`; return dispatch(await requestWorkflowJson<unknown>("POST", path, request), "POST", path); }
export async function getProgramDispatch(workspaceId: string, dispatchId: string) { const path = `${base(workspaceId)}/program-dispatches/${encodeURIComponent(dispatchId)}`; return dispatch(await requestWorkflowJson<unknown>("GET", path), "GET", path); }
// getProgramHandoff returns the backend-provided canonical Program Orchestrator
// handoff plus its exact raw response text. The raw text is the authoritative
// copy payload: the browser never reconstructs or re-assembles the handoff.
export async function getProgramHandoff(workspaceId: string, dispatchId: string): Promise<ProgramHandoffResult> {
  const path = `${base(workspaceId)}/program-dispatches/${encodeURIComponent(dispatchId)}/handoff`;
  const text = await requestWorkflowText("GET", path);
  let value: unknown;
  try { value = JSON.parse(text); }
  catch { return malformedWorkflowResponse("GET", path, "program handoff must be valid JSON"); }
  return { handoff: handoff(value, "GET", path), text };
}
export async function recordProgramDispatchResult(workspaceId: string, dispatchId: string, request: { expectedVersion: number; members: { memberId: string; outcome: "done" | "blocked"; branch: string; branchHeadSha: string; blocker: string }[]; laterIntegrationRisks: string }) { await requestWorkflowJson<unknown>("POST", `${base(workspaceId)}/program-dispatches/${encodeURIComponent(dispatchId)}/result`, request); }
