/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as RunsNewRouteImport } from './routes/runs/new'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as PlansNewRouteImport } from './routes/plans/new'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as RunsRunIdPrepareRouteImport } from './routes/runs/$runId/prepare'
import { Route as RunsRunIdIntakeRouteImport } from './routes/runs/$runId/intake'
import { Route as RunsRunIdExecuteRouteImport } from './routes/runs/$runId/execute'
import { Route as RunsRunIdAuditRouteImport } from './routes/runs/$runId/audit'
import { Route as PlansPlanIdPassesPassIdRouteImport } from './routes/plans/$planId/passes/$passId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansNewRoute = PlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdPrepareRoute = RunsRunIdPrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdIntakeRoute = RunsRunIdIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdExecuteRoute = RunsRunIdExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdAuditRoute = RunsRunIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const PlansPlanIdPassesPassIdRoute = PlansPlanIdPassesPassIdRouteImport.update({
  id: '/passes/$passId',
  path: '/passes/$passId',
  getParentRoute: () => PlansPlanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/new': typeof PlansNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/plans/': typeof PlansIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/execute': typeof RunsRunIdExecuteRoute
  '/runs/$runId/intake': typeof RunsRunIdIntakeRoute
  '/runs/$runId/prepare': typeof RunsRunIdPrepareRoute
  '/plans/$planId/passes/$passId': typeof PlansPlanIdPassesPassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/new': typeof PlansNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/plans': typeof PlansIndexRoute
  '/runs': typeof RunsIndexRoute
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/execute': typeof RunsRunIdExecuteRoute
  '/runs/$runId/intake': typeof RunsRunIdIntakeRoute
  '/runs/$runId/prepare': typeof RunsRunIdPrepareRoute
  '/plans/$planId/passes/$passId': typeof PlansPlanIdPassesPassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/new': typeof PlansNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/plans/': typeof PlansIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/execute': typeof RunsRunIdExecuteRoute
  '/runs/$runId/intake': typeof RunsRunIdIntakeRoute
  '/runs/$runId/prepare': typeof RunsRunIdPrepareRoute
  '/plans/$planId/passes/$passId': typeof PlansPlanIdPassesPassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plans/$planId'
    | '/plans/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/plans/'
    | '/runs/'
    | '/runs/$runId/audit'
    | '/runs/$runId/execute'
    | '/runs/$runId/intake'
    | '/runs/$runId/prepare'
    | '/plans/$planId/passes/$passId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans/$planId'
    | '/plans/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/plans'
    | '/runs'
    | '/runs/$runId/audit'
    | '/runs/$runId/execute'
    | '/runs/$runId/intake'
    | '/runs/$runId/prepare'
    | '/plans/$planId/passes/$passId'
  id:
    | '__root__'
    | '/'
    | '/plans/$planId'
    | '/plans/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/plans/'
    | '/runs/'
    | '/runs/$runId/audit'
    | '/runs/$runId/execute'
    | '/runs/$runId/intake'
    | '/runs/$runId/prepare'
    | '/plans/$planId/passes/$passId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansPlanIdRoute: typeof PlansPlanIdRouteWithChildren
  PlansNewRoute: typeof PlansNewRoute
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
  RunsNewRoute: typeof RunsNewRoute
  PlansIndexRoute: typeof PlansIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/new': {
      id: '/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/prepare': {
      id: '/runs/$runId/prepare'
      path: '/prepare'
      fullPath: '/runs/$runId/prepare'
      preLoaderRoute: typeof RunsRunIdPrepareRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/intake': {
      id: '/runs/$runId/intake'
      path: '/intake'
      fullPath: '/runs/$runId/intake'
      preLoaderRoute: typeof RunsRunIdIntakeRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/execute': {
      id: '/runs/$runId/execute'
      path: '/execute'
      fullPath: '/runs/$runId/execute'
      preLoaderRoute: typeof RunsRunIdExecuteRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/audit': {
      id: '/runs/$runId/audit'
      path: '/audit'
      fullPath: '/runs/$runId/audit'
      preLoaderRoute: typeof RunsRunIdAuditRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/plans/$planId/passes/$passId': {
      id: '/plans/$planId/passes/$passId'
      path: '/passes/$passId'
      fullPath: '/plans/$planId/passes/$passId'
      preLoaderRoute: typeof PlansPlanIdPassesPassIdRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
  }
}

interface PlansPlanIdRouteChildren {
  PlansPlanIdPassesPassIdRoute: typeof PlansPlanIdPassesPassIdRoute
}

const PlansPlanIdRouteChildren: PlansPlanIdRouteChildren = {
  PlansPlanIdPassesPassIdRoute: PlansPlanIdPassesPassIdRoute,
}

const PlansPlanIdRouteWithChildren = PlansPlanIdRoute._addFileChildren(
  PlansPlanIdRouteChildren,
)

interface RunsRunIdRouteChildren {
  RunsRunIdAuditRoute: typeof RunsRunIdAuditRoute
  RunsRunIdExecuteRoute: typeof RunsRunIdExecuteRoute
  RunsRunIdIntakeRoute: typeof RunsRunIdIntakeRoute
  RunsRunIdPrepareRoute: typeof RunsRunIdPrepareRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdAuditRoute: RunsRunIdAuditRoute,
  RunsRunIdExecuteRoute: RunsRunIdExecuteRoute,
  RunsRunIdIntakeRoute: RunsRunIdIntakeRoute,
  RunsRunIdPrepareRoute: RunsRunIdPrepareRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansPlanIdRoute: PlansPlanIdRouteWithChildren,
  PlansNewRoute: PlansNewRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
  RunsNewRoute: RunsNewRoute,
  PlansIndexRoute: PlansIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
