/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as RunsNewRouteImport } from './routes/runs/new'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as PlansNewRouteImport } from './routes/plans/new'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs/$runId/index'
import { Route as RunsRunIdSpecificationRouteImport } from './routes/runs/$runId/specification'
import { Route as RunsRunIdExecuteRouteImport } from './routes/runs/$runId/execute'
import { Route as RunsRunIdAuditRouteImport } from './routes/runs/$runId/audit'
import { Route as ProjectsProjectIdRefactorBacklogRouteImport } from './routes/projects/$projectId.refactor-backlog'
import { Route as PlansPlanIdPassesPassIdRouteImport } from './routes/plans/$planId.passes.$passId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansNewRoute = PlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdSpecificationRoute = RunsRunIdSpecificationRouteImport.update({
  id: '/specification',
  path: '/specification',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdExecuteRoute = RunsRunIdExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdAuditRoute = RunsRunIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const ProjectsProjectIdRefactorBacklogRoute =
  ProjectsProjectIdRefactorBacklogRouteImport.update({
    id: '/refactor-backlog',
    path: '/refactor-backlog',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const PlansPlanIdPassesPassIdRoute = PlansPlanIdPassesPassIdRouteImport.update({
  id: '/passes/$passId',
  path: '/passes/$passId',
  getParentRoute: () => PlansPlanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/new': typeof PlansNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/plans/': typeof PlansIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/projects/$projectId/refactor-backlog': typeof ProjectsProjectIdRefactorBacklogRoute
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/execute': typeof RunsRunIdExecuteRoute
  '/runs/$runId/specification': typeof RunsRunIdSpecificationRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
  '/plans/$planId/passes/$passId': typeof PlansPlanIdPassesPassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/new': typeof PlansNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/runs/new': typeof RunsNewRoute
  '/plans': typeof PlansIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/projects/$projectId/refactor-backlog': typeof ProjectsProjectIdRefactorBacklogRoute
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/execute': typeof RunsRunIdExecuteRoute
  '/runs/$runId/specification': typeof RunsRunIdSpecificationRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
  '/plans/$planId/passes/$passId': typeof PlansPlanIdPassesPassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/new': typeof PlansNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/plans/': typeof PlansIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/projects/$projectId/refactor-backlog': typeof ProjectsProjectIdRefactorBacklogRoute
  '/runs/$runId/audit': typeof RunsRunIdAuditRoute
  '/runs/$runId/execute': typeof RunsRunIdExecuteRoute
  '/runs/$runId/specification': typeof RunsRunIdSpecificationRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
  '/plans/$planId/passes/$passId': typeof PlansPlanIdPassesPassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plans/$planId'
    | '/plans/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/plans/'
    | '/projects/'
    | '/runs/'
    | '/projects/$projectId/refactor-backlog'
    | '/runs/$runId/audit'
    | '/runs/$runId/execute'
    | '/runs/$runId/specification'
    | '/runs/$runId/'
    | '/plans/$planId/passes/$passId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans/$planId'
    | '/plans/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/new'
    | '/plans'
    | '/projects'
    | '/runs'
    | '/projects/$projectId/refactor-backlog'
    | '/runs/$runId/audit'
    | '/runs/$runId/execute'
    | '/runs/$runId/specification'
    | '/runs/$runId'
    | '/plans/$planId/passes/$passId'
  id:
    | '__root__'
    | '/'
    | '/plans/$planId'
    | '/plans/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/plans/'
    | '/projects/'
    | '/runs/'
    | '/projects/$projectId/refactor-backlog'
    | '/runs/$runId/audit'
    | '/runs/$runId/execute'
    | '/runs/$runId/specification'
    | '/runs/$runId/'
    | '/plans/$planId/passes/$passId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansPlanIdRoute: typeof PlansPlanIdRouteWithChildren
  PlansNewRoute: typeof PlansNewRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
  RunsNewRoute: typeof RunsNewRoute
  PlansIndexRoute: typeof PlansIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/new': {
      id: '/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/specification': {
      id: '/runs/$runId/specification'
      path: '/specification'
      fullPath: '/runs/$runId/specification'
      preLoaderRoute: typeof RunsRunIdSpecificationRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/execute': {
      id: '/runs/$runId/execute'
      path: '/execute'
      fullPath: '/runs/$runId/execute'
      preLoaderRoute: typeof RunsRunIdExecuteRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/audit': {
      id: '/runs/$runId/audit'
      path: '/audit'
      fullPath: '/runs/$runId/audit'
      preLoaderRoute: typeof RunsRunIdAuditRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/projects/$projectId/refactor-backlog': {
      id: '/projects/$projectId/refactor-backlog'
      path: '/refactor-backlog'
      fullPath: '/projects/$projectId/refactor-backlog'
      preLoaderRoute: typeof ProjectsProjectIdRefactorBacklogRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/plans/$planId/passes/$passId': {
      id: '/plans/$planId/passes/$passId'
      path: '/passes/$passId'
      fullPath: '/plans/$planId/passes/$passId'
      preLoaderRoute: typeof PlansPlanIdPassesPassIdRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
  }
}

interface PlansPlanIdRouteChildren {
  PlansPlanIdPassesPassIdRoute: typeof PlansPlanIdPassesPassIdRoute
}

const PlansPlanIdRouteChildren: PlansPlanIdRouteChildren = {
  PlansPlanIdPassesPassIdRoute: PlansPlanIdPassesPassIdRoute,
}

const PlansPlanIdRouteWithChildren = PlansPlanIdRoute._addFileChildren(
  PlansPlanIdRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdRefactorBacklogRoute: typeof ProjectsProjectIdRefactorBacklogRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdRefactorBacklogRoute: ProjectsProjectIdRefactorBacklogRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface RunsRunIdRouteChildren {
  RunsRunIdAuditRoute: typeof RunsRunIdAuditRoute
  RunsRunIdExecuteRoute: typeof RunsRunIdExecuteRoute
  RunsRunIdSpecificationRoute: typeof RunsRunIdSpecificationRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdAuditRoute: RunsRunIdAuditRoute,
  RunsRunIdExecuteRoute: RunsRunIdExecuteRoute,
  RunsRunIdSpecificationRoute: RunsRunIdSpecificationRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansPlanIdRoute: PlansPlanIdRouteWithChildren,
  PlansNewRoute: PlansNewRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
  RunsNewRoute: RunsNewRoute,
  PlansIndexRoute: PlansIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
