// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package workflowgenerated

import (
	"database/sql"
)

type Artifact struct {
	ID                    int64         `json:"id"`
	ArtifactID            string        `json:"artifact_id"`
	OwnerType             string        `json:"owner_type"`
	PlanRowID             sql.NullInt64 `json:"plan_row_id"`
	RunRowID              sql.NullInt64 `json:"run_row_id"`
	ExecutionAttemptRowID sql.NullInt64 `json:"execution_attempt_row_id"`
	Kind                  string        `json:"kind"`
	RelativePath          string        `json:"relative_path"`
	MediaType             string        `json:"media_type"`
	Sha256                string        `json:"sha256"`
	SizeBytes             int64         `json:"size_bytes"`
	CreatedAt             string        `json:"created_at"`
}

type AuditDecision struct {
	ID                       int64  `json:"id"`
	AuditDecisionID          string `json:"audit_decision_id"`
	RunRowID                 int64  `json:"run_row_id"`
	AuditPacketArtifactRowID int64  `json:"audit_packet_artifact_row_id"`
	AuditedCommit            string `json:"audited_commit"`
	PacketSha256             string `json:"packet_sha256"`
	Decision                 string `json:"decision"`
	Rationale                string `json:"rationale"`
	CreatedAt                string `json:"created_at"`
}

type AuditPacket struct {
	ID                      int64          `json:"id"`
	AuditPacketID           string         `json:"audit_packet_id"`
	RunRowID                int64          `json:"run_row_id"`
	ImplementationActorKind string         `json:"implementation_actor_kind"`
	ExecutionAttemptRowID   sql.NullInt64  `json:"execution_attempt_row_id"`
	ArtifactRowID           int64          `json:"artifact_row_id"`
	BaseCommit              string         `json:"base_commit"`
	AuditedCommit           string         `json:"audited_commit"`
	PacketSha256            string         `json:"packet_sha256"`
	Status                  string         `json:"status"`
	StaleReason             string         `json:"stale_reason"`
	CreatedAt               string         `json:"created_at"`
	SupersededAt            sql.NullString `json:"superseded_at"`
}

type DeliveryTicket struct {
	ID                   int64         `json:"id"`
	TicketID             string        `json:"ticket_id"`
	WorkspaceRowID       int64         `json:"workspace_row_id"`
	ExternalPriority     int64         `json:"external_priority"`
	CurrentRevisionRowID sql.NullInt64 `json:"current_revision_row_id"`
	CreatedAt            string        `json:"created_at"`
	UpdatedAt            string        `json:"updated_at"`
}

type DeliveryTicketRevision struct {
	ID                      int64          `json:"id"`
	DeliveryTicketRowID     int64          `json:"delivery_ticket_row_id"`
	RevisionNumber          int64          `json:"revision_number"`
	ReplacesRevisionRowID   sql.NullInt64  `json:"replaces_revision_row_id"`
	CancellationReason      sql.NullString `json:"cancellation_reason"`
	RepoTarget              string         `json:"repo_target"`
	Branch                  string         `json:"branch"`
	BaseCommit              string         `json:"base_commit"`
	SourceClosureRowID      int64          `json:"source_closure_row_id"`
	SourcePath              string         `json:"source_path"`
	Goal                    string         `json:"goal"`
	Context                 string         `json:"context"`
	TransitionApplicability string         `json:"transition_applicability"`
	CreatedAt               string         `json:"created_at"`
}

type DeliveryTicketRevisionApproval struct {
	ID                     int64         `json:"id"`
	ApprovalID             string        `json:"approval_id"`
	RevisionRowID          int64         `json:"revision_row_id"`
	ApprovalKind           string        `json:"approval_kind"`
	ApprovalState          string        `json:"approval_state"`
	Rationale              string        `json:"rationale"`
	SourceClosureRowID     int64         `json:"source_closure_row_id"`
	CreatedAt              string        `json:"created_at"`
	AuthorityRevisionRowID sql.NullInt64 `json:"authority_revision_row_id"`
}

type DeliveryTicketRevisionDependency struct {
	ID                     int64  `json:"id"`
	RevisionRowID          int64  `json:"revision_row_id"`
	Sequence               int64  `json:"sequence"`
	DependsOnRevisionRowID int64  `json:"depends_on_revision_row_id"`
	Outcome                string `json:"outcome"`
	CreatedAt              string `json:"created_at"`
}

type DeliveryTicketRevisionMember struct {
	ID            int64          `json:"id"`
	RevisionRowID int64          `json:"revision_row_id"`
	Sequence      int64          `json:"sequence"`
	MemberKind    string         `json:"member_kind"`
	MemberPath    sql.NullString `json:"member_path"`
	MemberText    string         `json:"member_text"`
	CreatedAt     string         `json:"created_at"`
}

type DeliveryTicketSelection struct {
	ID                 int64         `json:"id"`
	SelectionID        string        `json:"selection_id"`
	WorkspaceRowID     int64         `json:"workspace_row_id"`
	State              string        `json:"state"`
	Rationale          string        `json:"rationale"`
	SourceClosureRowID sql.NullInt64 `json:"source_closure_row_id"`
	CreatedAt          string        `json:"created_at"`
	UpdatedAt          string        `json:"updated_at"`
}

type DeliveryTicketSelectionMember struct {
	ID             int64  `json:"id"`
	SelectionRowID int64  `json:"selection_row_id"`
	Sequence       int64  `json:"sequence"`
	RevisionRowID  int64  `json:"revision_row_id"`
	ApprovalRowID  int64  `json:"approval_row_id"`
	CreatedAt      string `json:"created_at"`
}

type ExecutionAttempt struct {
	ID                      int64          `json:"id"`
	AttemptID               string         `json:"attempt_id"`
	RunRowID                int64          `json:"run_row_id"`
	AttemptNumber           int64          `json:"attempt_number"`
	Adapter                 string         `json:"adapter"`
	Model                   string         `json:"model"`
	Status                  string         `json:"status"`
	ResultJson              string         `json:"result_json"`
	CreatedAt               string         `json:"created_at"`
	StartedAt               sql.NullString `json:"started_at"`
	FinishedAt              sql.NullString `json:"finished_at"`
	CancellationRequestedAt sql.NullString `json:"cancellation_requested_at"`
}

type ExecutionPackage struct {
	ID                     int64  `json:"id"`
	PackageID              string `json:"package_id"`
	SelectionRowID         int64  `json:"selection_row_id"`
	WorkspaceRowID         int64  `json:"workspace_row_id"`
	RepoTarget             string `json:"repo_target"`
	Branch                 string `json:"branch"`
	BaseCommit             string `json:"base_commit"`
	SourceClosureRowID     int64  `json:"source_closure_row_id"`
	AuthorityRevisionRowID int64  `json:"authority_revision_row_id"`
	PackageSha256          string `json:"package_sha256"`
	AuthoritySha256        string `json:"authority_sha256"`
	SourceSha256           string `json:"source_sha256"`
	DesignBriefSha256      string `json:"design_brief_sha256"`
	ExecutionSpecSha256    string `json:"execution_spec_sha256"`
	CreatedAt              string `json:"created_at"`
}

type ExecutionPackageApprovalBinding struct {
	ID                     int64  `json:"id"`
	PackageRowID           int64  `json:"package_row_id"`
	PackageMemberRowID     int64  `json:"package_member_row_id"`
	ApprovalRowID          int64  `json:"approval_row_id"`
	AuthorityRevisionRowID int64  `json:"authority_revision_row_id"`
	SourceClosureRowID     int64  `json:"source_closure_row_id"`
	ApprovalBasisSha256    string `json:"approval_basis_sha256"`
	CreatedAt              string `json:"created_at"`
}

type ExecutionPackageMember struct {
	ID                   int64  `json:"id"`
	PackageRowID         int64  `json:"package_row_id"`
	SelectionMemberRowID int64  `json:"selection_member_row_id"`
	Sequence             int64  `json:"sequence"`
	RevisionRowID        int64  `json:"revision_row_id"`
	MemberSha256         string `json:"member_sha256"`
	CreatedAt            string `json:"created_at"`
}

type FeatureWorkspace struct {
	ID                            int64         `json:"id"`
	WorkspaceID                   string        `json:"workspace_id"`
	ProjectRowID                  int64         `json:"project_row_id"`
	FeatureSlug                   string        `json:"feature_slug"`
	State                         string        `json:"state"`
	Version                       int64         `json:"version"`
	CurrentRouteStateRowID        sql.NullInt64 `json:"current_route_state_row_id"`
	CurrentAuthorityRevisionRowID sql.NullInt64 `json:"current_authority_revision_row_id"`
	CreatedAt                     string        `json:"created_at"`
	UpdatedAt                     string        `json:"updated_at"`
}

type FeatureWorkspaceAdmittedInput struct {
	ID                    int64          `json:"id"`
	AdmittedInputID       string         `json:"admitted_input_id"`
	WorkspaceRowID        int64          `json:"workspace_row_id"`
	Sequence              int64          `json:"sequence"`
	InputName             string         `json:"input_name"`
	InputRole             string         `json:"input_role"`
	SourceKind            string         `json:"source_kind"`
	ArtifactRowID         sql.NullInt64  `json:"artifact_row_id"`
	RetainedArtifactRowID sql.NullInt64  `json:"retained_artifact_row_id"`
	SourceClosureRowID    sql.NullInt64  `json:"source_closure_row_id"`
	ArtifactSha256        sql.NullString `json:"artifact_sha256"`
	SourceReference       string         `json:"source_reference"`
	CreatedAt             string         `json:"created_at"`
}

type FeatureWorkspaceAuthorityLayer struct {
	ID                     int64         `json:"id"`
	AuthorityRevisionRowID int64         `json:"authority_revision_row_id"`
	LayerKind              string        `json:"layer_kind"`
	Sequence               int64         `json:"sequence"`
	ArtifactRowID          sql.NullInt64 `json:"artifact_row_id"`
	RetainedArtifactRowID  sql.NullInt64 `json:"retained_artifact_row_id"`
	ArtifactSha256         string        `json:"artifact_sha256"`
	SourceClosureRowID     sql.NullInt64 `json:"source_closure_row_id"`
	CreatedAt              string        `json:"created_at"`
}

type FeatureWorkspaceAuthorityRevision struct {
	ID                  int64         `json:"id"`
	AuthorityRevisionID string        `json:"authority_revision_id"`
	WorkspaceRowID      int64         `json:"workspace_row_id"`
	RevisionNumber      int64         `json:"revision_number"`
	SourceClosureRowID  sql.NullInt64 `json:"source_closure_row_id"`
	CreatedAt           string        `json:"created_at"`
}

type FeatureWorkspaceDestination struct {
	ID                 int64          `json:"id"`
	DestinationID      string         `json:"destination_id"`
	WorkspaceRowID     int64          `json:"workspace_row_id"`
	Sequence           int64          `json:"sequence"`
	DestinationKind    string         `json:"destination_kind"`
	DestinationKey     string         `json:"destination_key"`
	RepoTarget         sql.NullString `json:"repo_target"`
	SourceClosureRowID sql.NullInt64  `json:"source_closure_row_id"`
	CreatedAt          string         `json:"created_at"`
}

type FeatureWorkspaceDiscoveryTicket struct {
	ID                int64  `json:"id"`
	DiscoveryTicketID string `json:"discovery_ticket_id"`
	WorkspaceRowID    int64  `json:"workspace_row_id"`
	TicketKey         string `json:"ticket_key"`
	Subject           string `json:"subject"`
	State             string `json:"state"`
	Version           int64  `json:"version"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type FeatureWorkspaceInvestigation struct {
	ID                    int64         `json:"id"`
	InvestigationID       string        `json:"investigation_id"`
	WorkspaceRowID        int64         `json:"workspace_row_id"`
	TicketRowID           sql.NullInt64 `json:"ticket_row_id"`
	Sequence              int64         `json:"sequence"`
	InvestigationKind     string        `json:"investigation_kind"`
	ArtifactRowID         sql.NullInt64 `json:"artifact_row_id"`
	RetainedArtifactRowID sql.NullInt64 `json:"retained_artifact_row_id"`
	ArtifactSha256        string        `json:"artifact_sha256"`
	SourceClosureRowID    sql.NullInt64 `json:"source_closure_row_id"`
	CreatedAt             string        `json:"created_at"`
}

type FeatureWorkspaceRouteState struct {
	ID               int64         `json:"id"`
	RouteStateID     string        `json:"route_state_id"`
	WorkspaceRowID   int64         `json:"workspace_row_id"`
	Sequence         int64         `json:"sequence"`
	WorkspaceVersion int64         `json:"workspace_version"`
	State            string        `json:"state"`
	TicketRowID      sql.NullInt64 `json:"ticket_row_id"`
	CreatedAt        string        `json:"created_at"`
}

type FeatureWorkspaceTicketDependency struct {
	TicketRowID          int64  `json:"ticket_row_id"`
	DependsOnTicketRowID int64  `json:"depends_on_ticket_row_id"`
	DependencyKind       string `json:"dependency_kind"`
	CreatedAt            string `json:"created_at"`
}

type FeatureWorkspaceTicketResolution struct {
	ID                    int64         `json:"id"`
	ResolutionID          string        `json:"resolution_id"`
	TicketRowID           int64         `json:"ticket_row_id"`
	Sequence              int64         `json:"sequence"`
	ResolutionKind        string        `json:"resolution_kind"`
	ArtifactRowID         sql.NullInt64 `json:"artifact_row_id"`
	RetainedArtifactRowID sql.NullInt64 `json:"retained_artifact_row_id"`
	ArtifactSha256        string        `json:"artifact_sha256"`
	SourceClosureRowID    sql.NullInt64 `json:"source_closure_row_id"`
	CreatedAt             string        `json:"created_at"`
}

type McpMutationResult struct {
	ID                      int64  `json:"id"`
	SurfaceContractID       string `json:"surface_contract_id"`
	ToolName                string `json:"tool_name"`
	MutationID              string `json:"mutation_id"`
	SurfaceManifestSha256   string `json:"surface_manifest_sha256"`
	SemanticIdentityVersion string `json:"semantic_identity_version"`
	SemanticRequestSha256   string `json:"semantic_request_sha256"`
	ResultKind              string `json:"result_kind"`
	ResultIdentityJson      string `json:"result_identity_json"`
	ResultSha256            string `json:"result_sha256"`
	CommittedAt             string `json:"committed_at"`
}

type OperationPacket struct {
	ID                       int64          `json:"id"`
	PacketID                 string         `json:"packet_id"`
	PacketSha256             string         `json:"packet_sha256"`
	SchemaVersion            string         `json:"schema_version"`
	Role                     string         `json:"role"`
	OperationID              string         `json:"operation_id"`
	SurfaceContractID        string         `json:"surface_contract_id"`
	ProjectID                string         `json:"project_id"`
	ReadinessState           string         `json:"readiness_state"`
	LifecycleState           string         `json:"lifecycle_state"`
	PriorPacketRowID         sql.NullInt64  `json:"prior_packet_row_id"`
	ReplacementPacketRowID   sql.NullInt64  `json:"replacement_packet_row_id"`
	CreatedAt                string         `json:"created_at"`
	SupersededAt             sql.NullString `json:"superseded_at"`
	ClosedAt                 sql.NullString `json:"closed_at"`
	PacketArtifactRowID      int64          `json:"packet_artifact_row_id"`
	CoordinatedPublicationID sql.NullString `json:"coordinated_publication_id"`
}

type OperationPacketArtifact struct {
	ID           int64  `json:"id"`
	ArtifactID   string `json:"artifact_id"`
	Kind         string `json:"kind"`
	RelativePath string `json:"relative_path"`
	MediaType    string `json:"media_type"`
	Sha256       string `json:"sha256"`
	SizeBytes    int64  `json:"size_bytes"`
	CreatedAt    string `json:"created_at"`
}

type OperationPacketArtifactBinding struct {
	ID                    int64         `json:"id"`
	PublicationID         string        `json:"publication_id"`
	PacketRowID           int64         `json:"packet_row_id"`
	Sequence              int64         `json:"sequence"`
	DependencyClass       string        `json:"dependency_class"`
	DependencyKey         string        `json:"dependency_key"`
	PacketArtifactRowID   sql.NullInt64 `json:"packet_artifact_row_id"`
	RetainedArtifactRowID sql.NullInt64 `json:"retained_artifact_row_id"`
	CreatedAt             string        `json:"created_at"`
}

type OperationPacketPublication struct {
	ID                             int64  `json:"id"`
	PublicationID                  string `json:"publication_id"`
	PacketRowID                    int64  `json:"packet_row_id"`
	PacketArtifactRowID            int64  `json:"packet_artifact_row_id"`
	MutationResultRowID            int64  `json:"mutation_result_row_id"`
	Namespace                      string `json:"namespace"`
	ManifestSha256                 string `json:"manifest_sha256"`
	ExpectedRetainedArtifactCount  int64  `json:"expected_retained_artifact_count"`
	ExpectedBindingCount           int64  `json:"expected_binding_count"`
	ExpectedDependencyCount        int64  `json:"expected_dependency_count"`
	ExpectedVaultRelationshipCount int64  `json:"expected_vault_relationship_count"`
	State                          string `json:"state"`
	CreatedAt                      string `json:"created_at"`
}

type OperationPacketRetainedArtifact struct {
	ID            int64  `json:"id"`
	PublicationID string `json:"publication_id"`
	ArtifactID    string `json:"artifact_id"`
	Kind          string `json:"kind"`
	RelativePath  string `json:"relative_path"`
	MediaType     string `json:"media_type"`
	Sha256        string `json:"sha256"`
	SizeBytes     int64  `json:"size_bytes"`
	CreatedAt     string `json:"created_at"`
}

type OperationPacketRetentionDependency struct {
	ID              int64          `json:"id"`
	PacketRowID     int64          `json:"packet_row_id"`
	DependencyClass string         `json:"dependency_class"`
	DependencyKey   string         `json:"dependency_key"`
	Required        int64          `json:"required"`
	Attached        int64          `json:"attached"`
	Retained        int64          `json:"retained"`
	OwnerIdentity   sql.NullString `json:"owner_identity"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type OperationPacketVaultRelationship struct {
	ID              int64  `json:"id"`
	PublicationID   string `json:"publication_id"`
	PacketRowID     int64  `json:"packet_row_id"`
	DependencyClass string `json:"dependency_class"`
	DependencyKey   string `json:"dependency_key"`
	OwnerIdentity   string `json:"owner_identity"`
	RetentionRowID  int64  `json:"retention_row_id"`
	ClosureRowID    int64  `json:"closure_row_id"`
	VaultRowID      int64  `json:"vault_row_id"`
	CommitOid       string `json:"commit_oid"`
	TreeOid         string `json:"tree_oid"`
	CreatedAt       string `json:"created_at"`
}

type Plan struct {
	ID              int64          `json:"id"`
	ProjectRowID    int64          `json:"project_row_id"`
	PlanID          string         `json:"plan_id"`
	FeatureSlug     string         `json:"feature_slug"`
	Status          string         `json:"status"`
	CanonicalSha256 string         `json:"canonical_sha256"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
}

type PlanPass struct {
	ID          int64          `json:"id"`
	PassID      string         `json:"pass_id"`
	PlanRowID   int64          `json:"plan_row_id"`
	PassNumber  int64          `json:"pass_number"`
	Name        string         `json:"name"`
	RepoTarget  string         `json:"repo_target"`
	Status      string         `json:"status"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	StartedAt   sql.NullString `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

type PlanPassDependency struct {
	PassRowID          int64  `json:"pass_row_id"`
	DependsOnPassRowID int64  `json:"depends_on_pass_row_id"`
	CreatedAt          string `json:"created_at"`
}

type PlanRepositoryTarget struct {
	ID                 int64  `json:"id"`
	PlanRowID          int64  `json:"plan_row_id"`
	Sequence           int64  `json:"sequence"`
	RepoTarget         string `json:"repo_target"`
	Branch             string `json:"branch"`
	PlanningBaseCommit string `json:"planning_base_commit"`
	CreatedAt          string `json:"created_at"`
}

type Project struct {
	ID          int64  `json:"id"`
	ProjectID   string `json:"project_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type ProjectNote struct {
	ID           int64  `json:"id"`
	NoteID       string `json:"note_id"`
	ProjectRowID int64  `json:"project_row_id"`
	Title        string `json:"title"`
	Body         string `json:"body"`
	Status       string `json:"status"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type ProjectRepositoryTarget struct {
	ProjectRowID int64  `json:"project_row_id"`
	RepoTarget   string `json:"repo_target"`
	CreatedAt    string `json:"created_at"`
}

type RepositoryBranchMutationLease struct {
	ID                      int64          `json:"id"`
	LeaseID                 string         `json:"lease_id"`
	RepoTarget              string         `json:"repo_target"`
	Branch                  string         `json:"branch"`
	OwnerKind               string         `json:"owner_kind"`
	OwnerIdentity           string         `json:"owner_identity"`
	State                   string         `json:"state"`
	UncertaintyState        string         `json:"uncertainty_state"`
	UncertaintyReason       sql.NullString `json:"uncertainty_reason"`
	ReconciliationState     string         `json:"reconciliation_state"`
	ReconciliationNote      sql.NullString `json:"reconciliation_note"`
	AcquiredAt              string         `json:"acquired_at"`
	ReleasedAt              sql.NullString `json:"released_at"`
	ReconciliationStartedAt sql.NullString `json:"reconciliation_started_at"`
	ReconciledAt            sql.NullString `json:"reconciled_at"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

type RepositoryTarget struct {
	RepoTarget           string         `json:"repo_target"`
	LocalPath            string         `json:"local_path"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	ConfiguredBranchRef  sql.NullString `json:"configured_branch_ref"`
	ConfigurationVersion int64          `json:"configuration_version"`
}

type Run struct {
	ID                    int64          `json:"id"`
	RunID                 string         `json:"run_id"`
	FeatureSlug           string         `json:"feature_slug"`
	RepoTarget            string         `json:"repo_target"`
	PlanRowID             sql.NullInt64  `json:"plan_row_id"`
	PlanPassRowID         sql.NullInt64  `json:"plan_pass_row_id"`
	RemediatesRunRowID    sql.NullInt64  `json:"remediates_run_row_id"`
	Status                string         `json:"status"`
	Branch                string         `json:"branch"`
	BaseCommit            string         `json:"base_commit"`
	CanonicalSha256       string         `json:"canonical_sha256"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	CompletedAt           sql.NullString `json:"completed_at"`
	ExecutionPackageRowID sql.NullInt64  `json:"execution_package_row_id"`
}

type SourceVault struct {
	ID           int64  `json:"id"`
	VaultID      string `json:"vault_id"`
	RepoTarget   string `json:"repo_target"`
	RelativePath string `json:"relative_path"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type SourceVaultClosure struct {
	ID              int64          `json:"id"`
	ClosureID       string         `json:"closure_id"`
	VaultRowID      int64          `json:"vault_row_id"`
	CommitOid       string         `json:"commit_oid"`
	TreeOid         string         `json:"tree_oid"`
	Generation      int64          `json:"generation"`
	RefName         string         `json:"ref_name"`
	State           string         `json:"state"`
	FailureReason   sql.NullString `json:"failure_reason"`
	ImportStartedAt string         `json:"import_started_at"`
	VerifiedAt      sql.NullString `json:"verified_at"`
	ReleasedAt      sql.NullString `json:"released_at"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type SourceVaultRetention struct {
	ID            int64          `json:"id"`
	RetentionID   string         `json:"retention_id"`
	ClosureRowID  int64          `json:"closure_row_id"`
	OwnerClass    string         `json:"owner_class"`
	OwnerIdentity string         `json:"owner_identity"`
	State         string         `json:"state"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
	ReleasedAt    sql.NullString `json:"released_at"`
}
