// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package workflowgenerated

import (
	"context"
	"database/sql"
)

const completePlan = `-- name: CompletePlan :one
UPDATE plans
SET
    status = 'completed',
    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND status = 'active'
RETURNING id, project_row_id, plan_id, feature_slug, status, canonical_sha256, created_at, updated_at, completed_at
`

func (q *Queries) CompletePlan(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRowContext(ctx, completePlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectRowID,
		&i.PlanID,
		&i.FeatureSlug,
		&i.Status,
		&i.CanonicalSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countIncompletePlanPasses = `-- name: CountIncompletePlanPasses :one
SELECT COUNT(*)
FROM plan_passes
WHERE plan_row_id = ? AND status <> 'completed'
`

func (q *Queries) CountIncompletePlanPasses(ctx context.Context, planRowID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIncompletePlanPasses, planRowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
    artifact_id,
    owner_type,
    plan_row_id,
    run_row_id,
    execution_attempt_row_id,
    kind,
    relative_path,
    media_type,
    sha256,
    size_bytes
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, artifact_id, owner_type, plan_row_id, run_row_id, execution_attempt_row_id, kind, relative_path, media_type, sha256, size_bytes, created_at
`

type CreateArtifactParams struct {
	ArtifactID            string        `json:"artifact_id"`
	OwnerType             string        `json:"owner_type"`
	PlanRowID             sql.NullInt64 `json:"plan_row_id"`
	RunRowID              sql.NullInt64 `json:"run_row_id"`
	ExecutionAttemptRowID sql.NullInt64 `json:"execution_attempt_row_id"`
	Kind                  string        `json:"kind"`
	RelativePath          string        `json:"relative_path"`
	MediaType             string        `json:"media_type"`
	Sha256                string        `json:"sha256"`
	SizeBytes             int64         `json:"size_bytes"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.ArtifactID,
		arg.OwnerType,
		arg.PlanRowID,
		arg.RunRowID,
		arg.ExecutionAttemptRowID,
		arg.Kind,
		arg.RelativePath,
		arg.MediaType,
		arg.Sha256,
		arg.SizeBytes,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.OwnerType,
		&i.PlanRowID,
		&i.RunRowID,
		&i.ExecutionAttemptRowID,
		&i.Kind,
		&i.RelativePath,
		&i.MediaType,
		&i.Sha256,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditDecision = `-- name: CreateAuditDecision :one
INSERT INTO audit_decisions (
    audit_decision_id,
    run_row_id,
    audit_packet_artifact_row_id,
    audited_commit,
    packet_sha256,
    decision,
    rationale
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, audit_decision_id, run_row_id, audit_packet_artifact_row_id, audited_commit, packet_sha256, decision, rationale, created_at
`

type CreateAuditDecisionParams struct {
	AuditDecisionID          string `json:"audit_decision_id"`
	RunRowID                 int64  `json:"run_row_id"`
	AuditPacketArtifactRowID int64  `json:"audit_packet_artifact_row_id"`
	AuditedCommit            string `json:"audited_commit"`
	PacketSha256             string `json:"packet_sha256"`
	Decision                 string `json:"decision"`
	Rationale                string `json:"rationale"`
}

func (q *Queries) CreateAuditDecision(ctx context.Context, arg CreateAuditDecisionParams) (AuditDecision, error) {
	row := q.db.QueryRowContext(ctx, createAuditDecision,
		arg.AuditDecisionID,
		arg.RunRowID,
		arg.AuditPacketArtifactRowID,
		arg.AuditedCommit,
		arg.PacketSha256,
		arg.Decision,
		arg.Rationale,
	)
	var i AuditDecision
	err := row.Scan(
		&i.ID,
		&i.AuditDecisionID,
		&i.RunRowID,
		&i.AuditPacketArtifactRowID,
		&i.AuditedCommit,
		&i.PacketSha256,
		&i.Decision,
		&i.Rationale,
		&i.CreatedAt,
	)
	return i, err
}

const createExecutionAttempt = `-- name: CreateExecutionAttempt :one
INSERT INTO execution_attempts (
    attempt_id,
    run_row_id,
    attempt_number,
    adapter,
    model,
    status
)
VALUES (?, ?, ?, ?, ?, 'pending')
RETURNING id, attempt_id, run_row_id, attempt_number, adapter, model, status, result_json, created_at, started_at, finished_at, cancellation_requested_at
`

type CreateExecutionAttemptParams struct {
	AttemptID     string `json:"attempt_id"`
	RunRowID      int64  `json:"run_row_id"`
	AttemptNumber int64  `json:"attempt_number"`
	Adapter       string `json:"adapter"`
	Model         string `json:"model"`
}

func (q *Queries) CreateExecutionAttempt(ctx context.Context, arg CreateExecutionAttemptParams) (ExecutionAttempt, error) {
	row := q.db.QueryRowContext(ctx, createExecutionAttempt,
		arg.AttemptID,
		arg.RunRowID,
		arg.AttemptNumber,
		arg.Adapter,
		arg.Model,
	)
	var i ExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.RunRowID,
		&i.AttemptNumber,
		&i.Adapter,
		&i.Model,
		&i.Status,
		&i.ResultJson,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancellationRequestedAt,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    project_row_id,
    plan_id,
    feature_slug,
    status,
    canonical_sha256
)
VALUES (?, ?, ?, 'active', ?)
RETURNING id, project_row_id, plan_id, feature_slug, status, canonical_sha256, created_at, updated_at, completed_at
`

type CreatePlanParams struct {
	ProjectRowID    int64  `json:"project_row_id"`
	PlanID          string `json:"plan_id"`
	FeatureSlug     string `json:"feature_slug"`
	CanonicalSha256 string `json:"canonical_sha256"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.ProjectRowID,
		arg.PlanID,
		arg.FeatureSlug,
		arg.CanonicalSha256,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectRowID,
		&i.PlanID,
		&i.FeatureSlug,
		&i.Status,
		&i.CanonicalSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createPlanPass = `-- name: CreatePlanPass :one
INSERT INTO plan_passes (
    pass_id,
    plan_row_id,
    pass_number,
    name,
    repo_target,
    status
)
VALUES (?, ?, ?, ?, ?, 'planned')
RETURNING id, pass_id, plan_row_id, pass_number, name, repo_target, status, created_at, updated_at, started_at, completed_at
`

type CreatePlanPassParams struct {
	PassID     string `json:"pass_id"`
	PlanRowID  int64  `json:"plan_row_id"`
	PassNumber int64  `json:"pass_number"`
	Name       string `json:"name"`
	RepoTarget string `json:"repo_target"`
}

func (q *Queries) CreatePlanPass(ctx context.Context, arg CreatePlanPassParams) (PlanPass, error) {
	row := q.db.QueryRowContext(ctx, createPlanPass,
		arg.PassID,
		arg.PlanRowID,
		arg.PassNumber,
		arg.Name,
		arg.RepoTarget,
	)
	var i PlanPass
	err := row.Scan(
		&i.ID,
		&i.PassID,
		&i.PlanRowID,
		&i.PassNumber,
		&i.Name,
		&i.RepoTarget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createPlanPassDependency = `-- name: CreatePlanPassDependency :exec
INSERT INTO plan_pass_dependencies (pass_row_id, depends_on_pass_row_id)
VALUES (?, ?)
`

type CreatePlanPassDependencyParams struct {
	PassRowID          int64 `json:"pass_row_id"`
	DependsOnPassRowID int64 `json:"depends_on_pass_row_id"`
}

func (q *Queries) CreatePlanPassDependency(ctx context.Context, arg CreatePlanPassDependencyParams) error {
	_, err := q.db.ExecContext(ctx, createPlanPassDependency, arg.PassRowID, arg.DependsOnPassRowID)
	return err
}

const createPlanRepositoryTarget = `-- name: CreatePlanRepositoryTarget :one
INSERT INTO plan_repository_targets (
    plan_row_id,
    sequence,
    repo_target,
    branch,
    planning_base_commit
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, plan_row_id, sequence, repo_target, branch, planning_base_commit, created_at
`

type CreatePlanRepositoryTargetParams struct {
	PlanRowID          int64  `json:"plan_row_id"`
	Sequence           int64  `json:"sequence"`
	RepoTarget         string `json:"repo_target"`
	Branch             string `json:"branch"`
	PlanningBaseCommit string `json:"planning_base_commit"`
}

func (q *Queries) CreatePlanRepositoryTarget(ctx context.Context, arg CreatePlanRepositoryTargetParams) (PlanRepositoryTarget, error) {
	row := q.db.QueryRowContext(ctx, createPlanRepositoryTarget,
		arg.PlanRowID,
		arg.Sequence,
		arg.RepoTarget,
		arg.Branch,
		arg.PlanningBaseCommit,
	)
	var i PlanRepositoryTarget
	err := row.Scan(
		&i.ID,
		&i.PlanRowID,
		&i.Sequence,
		&i.RepoTarget,
		&i.Branch,
		&i.PlanningBaseCommit,
		&i.CreatedAt,
	)
	return i, err
}

const createRepositoryTarget = `-- name: CreateRepositoryTarget :one
INSERT INTO repository_targets (repo_target, local_path)
VALUES (?, ?)
RETURNING repo_target, local_path, created_at, updated_at
`

type CreateRepositoryTargetParams struct {
	RepoTarget string `json:"repo_target"`
	LocalPath  string `json:"local_path"`
}

func (q *Queries) CreateRepositoryTarget(ctx context.Context, arg CreateRepositoryTargetParams) (RepositoryTarget, error) {
	row := q.db.QueryRowContext(ctx, createRepositoryTarget, arg.RepoTarget, arg.LocalPath)
	var i RepositoryTarget
	err := row.Scan(
		&i.RepoTarget,
		&i.LocalPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    run_id,
    feature_slug,
    repo_target,
    plan_row_id,
    plan_pass_row_id,
    remediates_run_row_id,
    status,
    branch,
    base_commit,
    canonical_sha256
)
VALUES (?, ?, ?, ?, ?, ?, 'created', ?, ?, ?)
RETURNING id, run_id, feature_slug, repo_target, plan_row_id, plan_pass_row_id, remediates_run_row_id, status, branch, base_commit, canonical_sha256, created_at, updated_at, completed_at
`

type CreateRunParams struct {
	RunID              string        `json:"run_id"`
	FeatureSlug        string        `json:"feature_slug"`
	RepoTarget         string        `json:"repo_target"`
	PlanRowID          sql.NullInt64 `json:"plan_row_id"`
	PlanPassRowID      sql.NullInt64 `json:"plan_pass_row_id"`
	RemediatesRunRowID sql.NullInt64 `json:"remediates_run_row_id"`
	Branch             string        `json:"branch"`
	BaseCommit         string        `json:"base_commit"`
	CanonicalSha256    string        `json:"canonical_sha256"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.RunID,
		arg.FeatureSlug,
		arg.RepoTarget,
		arg.PlanRowID,
		arg.PlanPassRowID,
		arg.RemediatesRunRowID,
		arg.Branch,
		arg.BaseCommit,
		arg.CanonicalSha256,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FeatureSlug,
		&i.RepoTarget,
		&i.PlanRowID,
		&i.PlanPassRowID,
		&i.RemediatesRunRowID,
		&i.Status,
		&i.Branch,
		&i.BaseCommit,
		&i.CanonicalSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getArtifactByArtifactID = `-- name: GetArtifactByArtifactID :one
SELECT id, artifact_id, owner_type, plan_row_id, run_row_id, execution_attempt_row_id, kind, relative_path, media_type, sha256, size_bytes, created_at
FROM artifacts
WHERE artifact_id = ?
`

func (q *Queries) GetArtifactByArtifactID(ctx context.Context, artifactID string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByArtifactID, artifactID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.OwnerType,
		&i.PlanRowID,
		&i.RunRowID,
		&i.ExecutionAttemptRowID,
		&i.Kind,
		&i.RelativePath,
		&i.MediaType,
		&i.Sha256,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditDecisionByDecisionID = `-- name: GetAuditDecisionByDecisionID :one
SELECT id, audit_decision_id, run_row_id, audit_packet_artifact_row_id, audited_commit, packet_sha256, decision, rationale, created_at
FROM audit_decisions
WHERE audit_decision_id = ?
`

func (q *Queries) GetAuditDecisionByDecisionID(ctx context.Context, auditDecisionID string) (AuditDecision, error) {
	row := q.db.QueryRowContext(ctx, getAuditDecisionByDecisionID, auditDecisionID)
	var i AuditDecision
	err := row.Scan(
		&i.ID,
		&i.AuditDecisionID,
		&i.RunRowID,
		&i.AuditPacketArtifactRowID,
		&i.AuditedCommit,
		&i.PacketSha256,
		&i.Decision,
		&i.Rationale,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionAttemptByAttemptID = `-- name: GetExecutionAttemptByAttemptID :one
SELECT id, attempt_id, run_row_id, attempt_number, adapter, model, status, result_json, created_at, started_at, finished_at, cancellation_requested_at
FROM execution_attempts
WHERE attempt_id = ?
`

func (q *Queries) GetExecutionAttemptByAttemptID(ctx context.Context, attemptID string) (ExecutionAttempt, error) {
	row := q.db.QueryRowContext(ctx, getExecutionAttemptByAttemptID, attemptID)
	var i ExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.RunRowID,
		&i.AttemptNumber,
		&i.Adapter,
		&i.Model,
		&i.Status,
		&i.ResultJson,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancellationRequestedAt,
	)
	return i, err
}

const getLatestExecutionAttemptByRun = `-- name: GetLatestExecutionAttemptByRun :one
SELECT id, attempt_id, run_row_id, attempt_number, adapter, model, status, result_json, created_at, started_at, finished_at, cancellation_requested_at
FROM execution_attempts
WHERE run_row_id = ?
ORDER BY attempt_number DESC
LIMIT 1
`

func (q *Queries) GetLatestExecutionAttemptByRun(ctx context.Context, runRowID int64) (ExecutionAttempt, error) {
	row := q.db.QueryRowContext(ctx, getLatestExecutionAttemptByRun, runRowID)
	var i ExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.RunRowID,
		&i.AttemptNumber,
		&i.Adapter,
		&i.Model,
		&i.Status,
		&i.ResultJson,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancellationRequestedAt,
	)
	return i, err
}

const getPlanByPlanID = `-- name: GetPlanByPlanID :one
SELECT id, project_row_id, plan_id, feature_slug, status, canonical_sha256, created_at, updated_at, completed_at
FROM plans
WHERE plan_id = ?
`

func (q *Queries) GetPlanByPlanID(ctx context.Context, planID string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByPlanID, planID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectRowID,
		&i.PlanID,
		&i.FeatureSlug,
		&i.Status,
		&i.CanonicalSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPlanPassByPassID = `-- name: GetPlanPassByPassID :one
SELECT id, pass_id, plan_row_id, pass_number, name, repo_target, status, created_at, updated_at, started_at, completed_at
FROM plan_passes
WHERE pass_id = ?
`

func (q *Queries) GetPlanPassByPassID(ctx context.Context, passID string) (PlanPass, error) {
	row := q.db.QueryRowContext(ctx, getPlanPassByPassID, passID)
	var i PlanPass
	err := row.Scan(
		&i.ID,
		&i.PassID,
		&i.PlanRowID,
		&i.PassNumber,
		&i.Name,
		&i.RepoTarget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPlanPassByPlanAndNumber = `-- name: GetPlanPassByPlanAndNumber :one
SELECT id, pass_id, plan_row_id, pass_number, name, repo_target, status, created_at, updated_at, started_at, completed_at
FROM plan_passes
WHERE plan_row_id = ? AND pass_number = ?
`

type GetPlanPassByPlanAndNumberParams struct {
	PlanRowID  int64 `json:"plan_row_id"`
	PassNumber int64 `json:"pass_number"`
}

func (q *Queries) GetPlanPassByPlanAndNumber(ctx context.Context, arg GetPlanPassByPlanAndNumberParams) (PlanPass, error) {
	row := q.db.QueryRowContext(ctx, getPlanPassByPlanAndNumber, arg.PlanRowID, arg.PassNumber)
	var i PlanPass
	err := row.Scan(
		&i.ID,
		&i.PassID,
		&i.PlanRowID,
		&i.PassNumber,
		&i.Name,
		&i.RepoTarget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPlanPassByRowID = `-- name: GetPlanPassByRowID :one
SELECT id, pass_id, plan_row_id, pass_number, name, repo_target, status, created_at, updated_at, started_at, completed_at
FROM plan_passes
WHERE id = ?
`

func (q *Queries) GetPlanPassByRowID(ctx context.Context, id int64) (PlanPass, error) {
	row := q.db.QueryRowContext(ctx, getPlanPassByRowID, id)
	var i PlanPass
	err := row.Scan(
		&i.ID,
		&i.PassID,
		&i.PlanRowID,
		&i.PassNumber,
		&i.Name,
		&i.RepoTarget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRepositoryTarget = `-- name: GetRepositoryTarget :one
SELECT repo_target, local_path, created_at, updated_at
FROM repository_targets
WHERE repo_target = ? COLLATE NOCASE
`

func (q *Queries) GetRepositoryTarget(ctx context.Context, repoTarget string) (RepositoryTarget, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryTarget, repoTarget)
	var i RepositoryTarget
	err := row.Scan(
		&i.RepoTarget,
		&i.LocalPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunByRowID = `-- name: GetRunByRowID :one
SELECT id, run_id, feature_slug, repo_target, plan_row_id, plan_pass_row_id, remediates_run_row_id, status, branch, base_commit, canonical_sha256, created_at, updated_at, completed_at
FROM runs
WHERE id = ?
`

func (q *Queries) GetRunByRowID(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByRowID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FeatureSlug,
		&i.RepoTarget,
		&i.PlanRowID,
		&i.PlanPassRowID,
		&i.RemediatesRunRowID,
		&i.Status,
		&i.Branch,
		&i.BaseCommit,
		&i.CanonicalSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunByRunID = `-- name: GetRunByRunID :one
SELECT id, run_id, feature_slug, repo_target, plan_row_id, plan_pass_row_id, remediates_run_row_id, status, branch, base_commit, canonical_sha256, created_at, updated_at, completed_at
FROM runs
WHERE run_id = ?
`

func (q *Queries) GetRunByRunID(ctx context.Context, runID string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByRunID, runID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FeatureSlug,
		&i.RepoTarget,
		&i.PlanRowID,
		&i.PlanPassRowID,
		&i.RemediatesRunRowID,
		&i.Status,
		&i.Branch,
		&i.BaseCommit,
		&i.CanonicalSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listArtifactsByExecutionAttempt = `-- name: ListArtifactsByExecutionAttempt :many
SELECT id, artifact_id, owner_type, plan_row_id, run_row_id, execution_attempt_row_id, kind, relative_path, media_type, sha256, size_bytes, created_at
FROM artifacts
WHERE execution_attempt_row_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListArtifactsByExecutionAttempt(ctx context.Context, executionAttemptRowID sql.NullInt64) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByExecutionAttempt, executionAttemptRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.OwnerType,
			&i.PlanRowID,
			&i.RunRowID,
			&i.ExecutionAttemptRowID,
			&i.Kind,
			&i.RelativePath,
			&i.MediaType,
			&i.Sha256,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByPlan = `-- name: ListArtifactsByPlan :many
SELECT id, artifact_id, owner_type, plan_row_id, run_row_id, execution_attempt_row_id, kind, relative_path, media_type, sha256, size_bytes, created_at
FROM artifacts
WHERE plan_row_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListArtifactsByPlan(ctx context.Context, planRowID sql.NullInt64) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByPlan, planRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.OwnerType,
			&i.PlanRowID,
			&i.RunRowID,
			&i.ExecutionAttemptRowID,
			&i.Kind,
			&i.RelativePath,
			&i.MediaType,
			&i.Sha256,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByRun = `-- name: ListArtifactsByRun :many
SELECT id, artifact_id, owner_type, plan_row_id, run_row_id, execution_attempt_row_id, kind, relative_path, media_type, sha256, size_bytes, created_at
FROM artifacts
WHERE run_row_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListArtifactsByRun(ctx context.Context, runRowID sql.NullInt64) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByRun, runRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.OwnerType,
			&i.PlanRowID,
			&i.RunRowID,
			&i.ExecutionAttemptRowID,
			&i.Kind,
			&i.RelativePath,
			&i.MediaType,
			&i.Sha256,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanPassDependencies = `-- name: ListPlanPassDependencies :many
SELECT pass_row_id, depends_on_pass_row_id, created_at
FROM plan_pass_dependencies
WHERE pass_row_id = ?
ORDER BY depends_on_pass_row_id
`

func (q *Queries) ListPlanPassDependencies(ctx context.Context, passRowID int64) ([]PlanPassDependency, error) {
	rows, err := q.db.QueryContext(ctx, listPlanPassDependencies, passRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanPassDependency{}
	for rows.Next() {
		var i PlanPassDependency
		if err := rows.Scan(&i.PassRowID, &i.DependsOnPassRowID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanPasses = `-- name: ListPlanPasses :many
SELECT id, pass_id, plan_row_id, pass_number, name, repo_target, status, created_at, updated_at, started_at, completed_at
FROM plan_passes
WHERE plan_row_id = ?
ORDER BY pass_number
`

func (q *Queries) ListPlanPasses(ctx context.Context, planRowID int64) ([]PlanPass, error) {
	rows, err := q.db.QueryContext(ctx, listPlanPasses, planRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanPass{}
	for rows.Next() {
		var i PlanPass
		if err := rows.Scan(
			&i.ID,
			&i.PassID,
			&i.PlanRowID,
			&i.PassNumber,
			&i.Name,
			&i.RepoTarget,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanRepositoryTargets = `-- name: ListPlanRepositoryTargets :many
SELECT id, plan_row_id, sequence, repo_target, branch, planning_base_commit, created_at
FROM plan_repository_targets
WHERE plan_row_id = ?
ORDER BY sequence
`

func (q *Queries) ListPlanRepositoryTargets(ctx context.Context, planRowID int64) ([]PlanRepositoryTarget, error) {
	rows, err := q.db.QueryContext(ctx, listPlanRepositoryTargets, planRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanRepositoryTarget{}
	for rows.Next() {
		var i PlanRepositoryTarget
		if err := rows.Scan(
			&i.ID,
			&i.PlanRowID,
			&i.Sequence,
			&i.RepoTarget,
			&i.Branch,
			&i.PlanningBaseCommit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryTargets = `-- name: ListRepositoryTargets :many
SELECT repo_target, local_path, created_at, updated_at
FROM repository_targets
ORDER BY repo_target COLLATE NOCASE
`

func (q *Queries) ListRepositoryTargets(ctx context.Context) ([]RepositoryTarget, error) {
	rows, err := q.db.QueryContext(ctx, listRepositoryTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepositoryTarget{}
	for rows.Next() {
		var i RepositoryTarget
		if err := rows.Scan(
			&i.RepoTarget,
			&i.LocalPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByPlanPass = `-- name: ListRunsByPlanPass :many
SELECT id, run_id, feature_slug, repo_target, plan_row_id, plan_pass_row_id, remediates_run_row_id, status, branch, base_commit, canonical_sha256, created_at, updated_at, completed_at
FROM runs
WHERE plan_pass_row_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListRunsByPlanPass(ctx context.Context, planPassRowID sql.NullInt64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByPlanPass, planPassRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FeatureSlug,
			&i.RepoTarget,
			&i.PlanRowID,
			&i.PlanPassRowID,
			&i.RemediatesRunRowID,
			&i.Status,
			&i.Branch,
			&i.BaseCommit,
			&i.CanonicalSha256,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextExecutionAttemptNumber = `-- name: NextExecutionAttemptNumber :one
SELECT COALESCE(MAX(attempt_number), 0) + 1
FROM execution_attempts
WHERE run_row_id = ?
`

func (q *Queries) NextExecutionAttemptNumber(ctx context.Context, runRowID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextExecutionAttemptNumber, runRowID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const transitionExecutionAttemptStatus = `-- name: TransitionExecutionAttemptStatus :one
UPDATE execution_attempts
SET
    status = ?4,
    result_json = ?,
    started_at = CASE
        WHEN sqlc.arg(status) IN ('running', 'cancelled') THEN COALESCE(started_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        ELSE started_at
    END,
    finished_at = CASE
        WHEN sqlc.arg(status) IN ('succeeded', 'failed', 'cancelled', 'timed_out') THEN strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
        ELSE NULL
    END,
    cancellation_requested_at = CASE
        WHEN ?4 = 'cancelled' THEN COALESCE(cancellation_requested_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        ELSE cancellation_requested_at
    END
WHERE attempt_id = ? AND status = ?
RETURNING id, attempt_id, run_row_id, attempt_number, adapter, model, status, result_json, created_at, started_at, finished_at, cancellation_requested_at
`

type TransitionExecutionAttemptStatusParams struct {
	Status     string `json:"status"`
	ResultJson string `json:"result_json"`
	AttemptID  string `json:"attempt_id"`
	Status_2   string `json:"status_2"`
}

func (q *Queries) TransitionExecutionAttemptStatus(ctx context.Context, arg TransitionExecutionAttemptStatusParams) (ExecutionAttempt, error) {
	row := q.db.QueryRowContext(ctx, transitionExecutionAttemptStatus,
		arg.Status,
		arg.ResultJson,
		arg.AttemptID,
		arg.Status_2,
	)
	var i ExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.RunRowID,
		&i.AttemptNumber,
		&i.Adapter,
		&i.Model,
		&i.Status,
		&i.ResultJson,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancellationRequestedAt,
	)
	return i, err
}

const transitionPlanPassStatus = `-- name: TransitionPlanPassStatus :one
UPDATE plan_passes
SET
    status = ?,
    started_at = CASE
        WHEN ? = 'in_progress' THEN COALESCE(started_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        ELSE started_at
    END,
    completed_at = CASE
        WHEN ? = 'completed' THEN strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
        ELSE NULL
    END,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE pass_id = ? AND status = ?
RETURNING id, pass_id, plan_row_id, pass_number, name, repo_target, status, created_at, updated_at, started_at, completed_at
`

type TransitionPlanPassStatusParams struct {
	Status   string      `json:"status"`
	Column2  interface{} `json:"column_2"`
	Column3  interface{} `json:"column_3"`
	PassID   string      `json:"pass_id"`
	Status_2 string      `json:"status_2"`
}

func (q *Queries) TransitionPlanPassStatus(ctx context.Context, arg TransitionPlanPassStatusParams) (PlanPass, error) {
	row := q.db.QueryRowContext(ctx, transitionPlanPassStatus,
		arg.Status,
		arg.Column2,
		arg.Column3,
		arg.PassID,
		arg.Status_2,
	)
	var i PlanPass
	err := row.Scan(
		&i.ID,
		&i.PassID,
		&i.PlanRowID,
		&i.PassNumber,
		&i.Name,
		&i.RepoTarget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const transitionRunStatus = `-- name: TransitionRunStatus :one
UPDATE runs
SET
    status = ?,
    completed_at = CASE
        WHEN ? = 'completed' THEN strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
        ELSE NULL
    END,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE run_id = ? AND status = ?
RETURNING id, run_id, feature_slug, repo_target, plan_row_id, plan_pass_row_id, remediates_run_row_id, status, branch, base_commit, canonical_sha256, created_at, updated_at, completed_at
`

type TransitionRunStatusParams struct {
	Status   string      `json:"status"`
	Column2  interface{} `json:"column_2"`
	RunID    string      `json:"run_id"`
	Status_2 string      `json:"status_2"`
}

func (q *Queries) TransitionRunStatus(ctx context.Context, arg TransitionRunStatusParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, transitionRunStatus,
		arg.Status,
		arg.Column2,
		arg.RunID,
		arg.Status_2,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FeatureSlug,
		&i.RepoTarget,
		&i.PlanRowID,
		&i.PlanPassRowID,
		&i.RemediatesRunRowID,
		&i.Status,
		&i.Branch,
		&i.BaseCommit,
		&i.CanonicalSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
