import { asWorkflowRecord, malformedWorkflowResponse, requestWorkflowJson, requiredWorkflowArray, requiredWorkflowInteger, requiredWorkflowString, type WorkflowHttpMethod, type WorkflowJsonRecord } from "@/features/workflow-api";
import type { PublishTicketRevisionRequest, TicketAdmissionRequest, TicketDetail, TicketFrontier, TicketSelection } from "./types";

function record(value: unknown, method: WorkflowHttpMethod, path: string, context: string): WorkflowJsonRecord { return asWorkflowRecord(value, method, path, context); }
function nullableInteger(value: unknown, method: WorkflowHttpMethod, path: string, field: string): number | null { if (value === null || value === undefined) return null; if (!Number.isInteger(value)) return malformedWorkflowResponse(method, path, `${field} must be an integer or null`); return value as number; }

function frontier(value: unknown, method: WorkflowHttpMethod, path: string): TicketFrontier {
  const item = record(value, method, path, "ticket frontier");
  return { workspaceId: requiredWorkflowString(item, "workspaceId", method, path, "ticket frontier"), entries: requiredWorkflowArray(item, "entries", method, path, "ticket frontier").map((entry) => { const value = record(entry, method, path, "frontier entry"); const tie = value.tieWithPrevious === undefined ? undefined : record(value.tieWithPrevious, method, path, "tie reason"); return { ticketId: requiredWorkflowString(value, "ticketId", method, path, "frontier entry"), revisionRowId: requiredWorkflowInteger(value, "revisionRowId", method, path, "frontier entry", 1), revisionNumber: requiredWorkflowInteger(value, "revisionNumber", method, path, "frontier entry", 1), externalPriority: requiredWorkflowInteger(value, "externalPriority", method, path, "frontier entry"), createdAt: requiredWorkflowString(value, "createdAt", method, path, "frontier entry", true), repoTarget: requiredWorkflowString(value, "repoTarget", method, path, "frontier entry"), branch: requiredWorkflowString(value, "branch", method, path, "frontier entry"), sourceClosureRowId: requiredWorkflowInteger(value, "sourceClosureRowId", method, path, "frontier entry", 1), tieWithPrevious: tie ? { previousTicketId: requiredWorkflowString(tie, "previousTicketId", method, path, "tie reason"), rule: requiredWorkflowString(tie, "rule", method, path, "tie reason") as "earlier_creation_time" | "stable_ticket_id" } : undefined }; }) };
}

function detail(value: unknown, method: WorkflowHttpMethod, path: string): TicketDetail {
  const item = record(value, method, path, "ticket detail"); const ticket = record(item.ticket, method, path, "ticket"); const readiness = record(ticket.readiness, method, path, "ticket readiness");
  const revisionValue = ticket.revision === null ? null : record(ticket.revision, method, path, "ticket revision");
  const history = requiredWorkflowArray(item, "history", method, path, "ticket detail").map((historyItem) => { const value = record(historyItem, method, path, "ticket history"); return { rowId: requiredWorkflowInteger(value, "rowId", method, path, "ticket history", 1), number: requiredWorkflowInteger(value, "number", method, path, "ticket history", 1), sourceClosureRowId: requiredWorkflowInteger(value, "sourceClosureRowId", method, path, "ticket history", 1), goal: requiredWorkflowString(value, "goal", method, path, "ticket history") }; });
  return { ticketId: requiredWorkflowString(ticket, "ticketId", method, path, "ticket"), externalPriority: requiredWorkflowInteger(ticket, "externalPriority", method, path, "ticket"), revision: revisionValue ? { rowId: requiredWorkflowInteger(revisionValue, "rowId", method, path, "ticket revision", 1), number: requiredWorkflowInteger(revisionValue, "number", method, path, "ticket revision", 1), sourceClosureRowId: requiredWorkflowInteger(revisionValue, "sourceClosureRowId", method, path, "ticket revision", 1), goal: requiredWorkflowString(revisionValue, "goal", method, path, "ticket revision"), approvals: requiredWorkflowArray(revisionValue, "approvals", method, path, "ticket revision").map((approval) => { const value = record(approval, method, path, "ticket approval"); return { approvalId: requiredWorkflowString(value, "approvalId", method, path, "ticket approval"), state: requiredWorkflowString(value, "state", method, path, "ticket approval"), authorityRevisionId: nullableInteger(value.authorityRevisionId, method, path, "authorityRevisionId"), sourceClosureRowId: requiredWorkflowInteger(value, "sourceClosureRowId", method, path, "ticket approval", 1), rationale: requiredWorkflowString(value, "rationale", method, path, "ticket approval", true) }; }) } : null, readiness: { ready: Boolean(readiness.ready), selected: Boolean(readiness.selected), reasons: requiredWorkflowArray(readiness, "reasons", method, path, "ticket readiness").map((reason) => { if (typeof reason !== "string") return malformedWorkflowResponse(method, path, "ticket readiness reasons must be strings"); return reason; }) }, history };
}

export async function getTicketFrontier(workspaceId: string, packetId: string, operationId: string): Promise<TicketFrontier> { const path = `/api/feature-workspaces/${encodeURIComponent(workspaceId)}/tickets/frontier?packetId=${encodeURIComponent(packetId)}&operationId=${encodeURIComponent(operationId)}`; return frontier(await requestWorkflowJson<unknown>("GET", path), "GET", path); }
export async function getTicket(ticketId: string): Promise<TicketDetail> { const path = `/api/delivery-tickets/${encodeURIComponent(ticketId)}`; return detail(await requestWorkflowJson<unknown>("GET", path), "GET", path); }
export async function publishTicketRevision(workspaceId: string, ticketId: string, request: PublishTicketRevisionRequest): Promise<void> { await requestWorkflowJson<unknown>("POST", `/api/feature-workspaces/${encodeURIComponent(workspaceId)}/tickets/${encodeURIComponent(ticketId)}/revisions`, request); }
export async function approveTicket(ticketId: string, request: TicketAdmissionRequest & { revisionRowId: number; authorityRevisionId: string; sourceClosureRowId: number; rationale: string }): Promise<void> { await requestWorkflowJson<unknown>("POST", `/api/delivery-tickets/${encodeURIComponent(ticketId)}/approvals`, request); }
export async function updateTicketPriority(workspaceId: string, ticketId: string, request: TicketAdmissionRequest & { externalPriority: number }): Promise<void> { await requestWorkflowJson<unknown>("PATCH", `/api/delivery-tickets/${encodeURIComponent(ticketId)}/priority`, { ...request, workspaceId }); }
export async function selectTicket(workspaceId: string, request: TicketAdmissionRequest & { ticketId: string; revisionRowId: number; rationale: string }): Promise<TicketSelection> { const path = `/api/feature-workspaces/${encodeURIComponent(workspaceId)}/tickets/selection`; const response = record(await requestWorkflowJson<unknown>("POST", path, request), "POST", path, "ticket selection"); const selection = record(response.selection, "POST", path, "ticket selection"); const selectedTicket = record(response.selectedTicket, "POST", path, "selected ticket"); return { selectionId: requiredWorkflowString(selection, "selectionId", "POST", path, "ticket selection"), state: requiredWorkflowString(selection, "state", "POST", path, "ticket selection"), rationale: requiredWorkflowString(selection, "rationale", "POST", path, "ticket selection"), createdAt: requiredWorkflowString(selection, "createdAt", "POST", path, "ticket selection", true), selectedTicket: { ticketId: requiredWorkflowString(selectedTicket, "ticketId", "POST", path, "selected ticket"), revisionRowId: requiredWorkflowInteger(selectedTicket, "revisionRowId", "POST", path, "selected ticket", 1), revisionNumber: requiredWorkflowInteger(selectedTicket, "revisionNumber", "POST", path, "selected ticket", 1), approvalRowId: requiredWorkflowInteger(selectedTicket, "approvalRowId", "POST", path, "selected ticket", 1) } }; }
