import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import {
  admitIntegrationMergeResult, cancelProgramMember, createProgramDispatch, generateIntegrationAssignment, getIntegrationAssignment, getIntegrationAssignmentResult, getIntegrationFailure, getProgramDispatch, getProgramHandoff, listProgramMembers, prepareProgramMember, recordProgramDispatchResult, verifyIntegrationAssignment,
  type AdmitIntegrationMergeResultRequest, type ProgramDispatch, type ProgramIntegrationAssignment, type ProgramIntegrationFailure, type ProgramIntegrationMergeResult, type ProgramIntegrationVerification,
} from "@/features/relay-programs";

const key = (workspaceId: string) => ["feature-workspaces", workspaceId, "program-members"] as const;
type Result = { outcome: "done" | "blocked"; branch: string; branchHeadSha: string; blocker: string };
type OutcomeStatus = "passed" | "failed";
type MergeRow = { status: OutcomeStatus; evidence: string };
type MergeForm = { integratedCommit: string; preservationIdentity: string; conflictResolution: "clean" | "mechanically_resolved" | "material_conflict"; conflictEvidence: string; rows: Record<string, MergeRow> };
type CopyStatus = "idle" | "copying" | "copied" | "failed";
const error = (value: unknown) => value instanceof Error ? value.message : "Program workspace action failed.";
const emptyResult = (): Result => ({ outcome: "done", branch: "", branchHeadSha: "", blocker: "" });
const normalizedResult = (memberId: string, result: Result) => result.outcome === "done" ? { memberId, outcome: result.outcome, branch: result.branch.trim(), branchHeadSha: result.branchHeadSha.trim().toLowerCase(), blocker: "" } : { memberId, outcome: result.outcome, branch: "", branchHeadSha: "", blocker: result.blocker.trim() };
const emptyMergeForm = (assignment: ProgramIntegrationAssignment): MergeForm => ({ integratedCommit: "", preservationIdentity: "", conflictResolution: "clean", conflictEvidence: "", rows: Object.fromEntries([...assignment.document.combinedValidation.map((v) => [`v:${v.sequence}`, { status: "passed", evidence: "" } as MergeRow]), ...assignment.document.requiredEvidence.map((v) => [`e:${v.sequence}`, { status: "passed", evidence: "" } as MergeRow])]) });
const mergeFormValid = (assignment: ProgramIntegrationAssignment, form: MergeForm) => /^[0-9a-f]{40}$/.test(form.integratedCommit.trim()) && form.preservationIdentity.trim().length > 0 && form.preservationIdentity.trim() === form.preservationIdentity && form.conflictEvidence.trim() === form.conflictEvidence && ((form.conflictResolution === "clean" && form.conflictEvidence === "") || (form.conflictResolution === "mechanically_resolved" && (() => { try { const evidence = JSON.parse(form.conflictEvidence); return evidence?.version === 1 && evidence?.integrated_commit === form.integratedCommit.trim() && typeof evidence?.assignment_id === "string" && Array.isArray(evidence?.conflicts) && evidence.conflicts.length > 0; } catch { return false; } })()) || (form.conflictResolution === "material_conflict" && form.conflictEvidence.length > 0)) && assignment.document.combinedValidation.every((v) => form.rows[`v:${v.sequence}`]?.evidence.trim().length > 0) && assignment.document.requiredEvidence.every((v) => form.rows[`e:${v.sequence}`]?.evidence.trim().length > 0);

export function RelayFeatureWorkspaceProgram({ workspaceId, expectedVersion }: { workspaceId: string; expectedVersion: number }) {
  const client = useQueryClient();
  const [packageId, setPackageId] = React.useState(""); const [selected, setSelected] = React.useState<string[]>([]); const [dispatch, setDispatch] = React.useState<ProgramDispatch | null>(null); const [results, setResults] = React.useState<Record<string, Result>>({}); const [risks, setRisks] = React.useState(""); const [message, setMessage] = React.useState<string | null>(null);
  const [integrations, setIntegrations] = React.useState<ProgramIntegrationAssignment[]>([]); const [integrationSelection, setIntegrationSelection] = React.useState<string[]>([]); const [mergeResults, setMergeResults] = React.useState<Record<string, ProgramIntegrationMergeResult | null>>({}); const [verifications, setVerifications] = React.useState<Record<string, ProgramIntegrationVerification | null>>({}); const [failures, setFailures] = React.useState<Record<string, ProgramIntegrationFailure | null>>({}); const [mergeForms, setMergeForms] = React.useState<Record<string, MergeForm>>({}); const [copyStates, setCopyStates] = React.useState<Record<string, CopyStatus>>({}); const [integrationMessage, setIntegrationMessage] = React.useState<string | null>(null);
  const members = useQuery({ queryKey: key(workspaceId), queryFn: () => listProgramMembers(workspaceId), staleTime: 5_000 }); const refresh = () => client.invalidateQueries({ queryKey: key(workspaceId) });
  const prepare = useMutation({ mutationFn: () => prepareProgramMember(workspaceId, { packageId: packageId.trim(), expectedVersion }), onSuccess: () => { setPackageId(""); setMessage(null); void refresh(); }, onError: (e) => setMessage(error(e)) });
  const cancel = useMutation({ mutationFn: (id: string) => cancelProgramMember(workspaceId, id, expectedVersion), onSuccess: () => { setSelected([]); void refresh(); }, onError: (e) => setMessage(error(e)) });
  const create = useMutation({ mutationFn: () => createProgramDispatch(workspaceId, { expectedVersion, memberIds: selected }), onSuccess: (value) => { setDispatch(value); setSelected([]); setResults({}); setRisks(""); setIntegrationSelection([]); void refresh(); }, onError: (e) => setMessage(error(e)) });
  const read = useMutation({ mutationFn: () => dispatch ? getProgramDispatch(workspaceId, dispatch.id) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: setDispatch, onError: (e) => setMessage(error(e)) });
  const record = useMutation({ mutationFn: () => dispatch ? recordProgramDispatchResult(workspaceId, dispatch.id, { expectedVersion, laterIntegrationRisks: risks, members: dispatch.members.map((member) => normalizedResult(member.id, results[member.id] ?? emptyResult())) }) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: () => void read.mutateAsync(), onError: (e) => setMessage(error(e)) });
  const generate = useMutation({ mutationFn: (memberIds: string[]) => dispatch ? generateIntegrationAssignment(workspaceId, dispatch.id, { expectedVersion, memberIds }) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: (assignment) => { setIntegrations((all) => [...all, assignment]); setMergeForms((all) => ({ ...all, [assignment.assignmentId]: emptyMergeForm(assignment) })); setIntegrationSelection([]); setIntegrationMessage(null); }, onError: (e) => setIntegrationMessage(error(e)) });
  const admit = useMutation({ mutationFn: (assignmentId: string) => { const assignment = integrations.find((a) => a.assignmentId === assignmentId); const form = mergeForms[assignmentId]; if (!assignment || !form) return Promise.reject(new Error("Read the Assignment first.")); const request: AdmitIntegrationMergeResultRequest = { expectedVersion, integratedCommit: form.integratedCommit.trim(), preservationIdentity: form.preservationIdentity.trim(), conflictResolution: form.conflictResolution, conflictEvidence: form.conflictEvidence, validations: assignment.document.combinedValidation.map((v) => ({ command: v.command, expected: v.expected, status: form.rows[`v:${v.sequence}`]?.status ?? "passed", evidence: form.rows[`v:${v.sequence}`]?.evidence.trim() ?? "" })), evidence: assignment.document.requiredEvidence.map((v) => ({ kind: v.kind, obligation: v.obligation, status: form.rows[`e:${v.sequence}`]?.status ?? "passed", evidence: form.rows[`e:${v.sequence}`]?.evidence.trim() ?? "" })) }; return dispatch ? admitIntegrationMergeResult(workspaceId, dispatch.id, assignmentId, request) : Promise.reject(new Error("Create a dispatch first.")); }, onSuccess: (result, assignmentId) => { setMergeResults((all) => ({ ...all, [result.assignmentId]: result })); setIntegrations((all) => all.map((a) => a.assignmentId === assignmentId ? { ...a, status: "admitted" } : a)); setIntegrationMessage(null); }, onError: (e) => setIntegrationMessage(error(e)) });
  const verify = useMutation({ mutationFn: (assignmentId: string) => dispatch ? verifyIntegrationAssignment(workspaceId, dispatch.id, assignmentId, expectedVersion) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: (value) => { setVerifications((all) => ({ ...all, [value.assignmentId]: value })); setIntegrations((all) => all.map((a) => a.assignmentId === value.assignmentId ? { ...a, status: value.outcome === "passed" ? "verified" : "failed" } : a)); if (value.outcome === "failed") setFailures((all) => ({ ...all, [value.assignmentId]: { verificationId: value.verificationId, assignmentId: value.assignmentId, dispatchId: value.dispatchId, failureReason: value.failureReason } })); setIntegrationMessage(null); }, onError: (e) => setIntegrationMessage(error(e)) });
  const readAssignment = useMutation({ mutationFn: (assignmentId: string) => dispatch ? getIntegrationAssignment(workspaceId, dispatch.id, assignmentId) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: (assignment) => { setIntegrations((all) => all.map((a) => a.assignmentId === assignment.assignmentId ? assignment : a)); setIntegrationMessage(null); }, onError: (e) => setIntegrationMessage(error(e)) });
  const readFailure = useMutation({ mutationFn: (assignmentId: string) => dispatch ? getIntegrationFailure(workspaceId, dispatch.id, assignmentId) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: (value) => { setFailures((all) => ({ ...all, [value.assignmentId]: value })); setIntegrationMessage(null); }, onError: (e) => setIntegrationMessage(error(e)) });
  const prepared = members.data?.filter((member) => member.state === "prepared") ?? []; const baseline = prepared[0]; const valid = dispatch?.status === "dispatched" && dispatch.members.every((member) => { const result = normalizedResult(member.id, results[member.id] ?? emptyResult()); return result.outcome === "done" ? result.branch.length > 0 && /^[0-9a-f]{40}$/.test(result.branchHeadSha) : result.blocker.length > 0; });
  const assignments = dispatch ? integrations.filter((a) => a.dispatchId === dispatch.id) : [];
  const boundMembers = new Set(assignments.filter((a) => a.status !== "failed").flatMap((a) => a.document.constituents.map((c) => c.memberId)));
  const eligibleCandidates = dispatch && dispatch.status === "reported" ? dispatch.members.filter((m) => m.outcome === "done" && !boundMembers.has(m.id)) : [];
  const setMergeRow = (assignmentId: string, key: string, patch: Partial<MergeRow>) => setMergeForms((all) => { const form = all[assignmentId]; return form ? { ...all, [assignmentId]: { ...form, rows: { ...form.rows, [key]: { ...form.rows[key], ...patch } } } } : all; });
  const setMergeField = (assignmentId: string, field: "integratedCommit" | "preservationIdentity" | "conflictEvidence" | "conflictResolution", value: string) => setMergeForms((all) => { const form = all[assignmentId]; return form ? { ...all, [assignmentId]: { ...form, [field]: value } } : all; });
  const copyAssignment = (assignment: ProgramIntegrationAssignment) => { setCopyStates((all) => ({ ...all, [assignment.assignmentId]: "copying" })); void getIntegrationAssignmentResult(workspaceId, dispatch?.id ?? "", assignment.assignmentId).then(async ({ assignment: read, text }) => { await navigator.clipboard?.writeText(text); setIntegrations((all) => all.map((a) => a.assignmentId === assignment.assignmentId ? read : a)); setCopyStates((all) => ({ ...all, [assignment.assignmentId]: "copied" })); }).catch(() => setCopyStates((all) => ({ ...all, [assignment.assignmentId]: "failed" }))); };
  return <section aria-labelledby="program-workspace" className="rounded border border-[var(--relay-row-border)] bg-[var(--relay-panel-bg)] p-6"><h2 id="program-workspace" className="font-semibold">Program workspace</h2><p className="mt-1 text-sm text-muted-foreground">Prepare one eligible approved current package at a time. Members require a common repository, branch, and base commit before immutable handoff to the external Program Orchestrator.</p>{message ? <p role="alert" className="mt-3 text-sm text-destructive">{message}</p> : null}
    <form className="mt-4 flex gap-2" onSubmit={(e) => { e.preventDefault(); prepare.mutate(); }}><label className="sr-only" htmlFor="program-package">Approved package ID</label><input id="program-package" className="rounded border bg-background px-3 py-2 text-sm" placeholder="Approved package ID" value={packageId} onChange={(e) => setPackageId(e.target.value)} /><Button type="submit" disabled={!packageId.trim() || prepare.isPending}>Prepare package</Button></form>
    <h3 className="mt-5 font-medium">Prepared members</h3>{members.isLoading ? <p className="mt-2 text-sm">Loading prepared members…</p> : prepared.length ? <><p className="mt-2 text-sm text-muted-foreground">Common baseline: {baseline?.repoTarget} @ {baseline?.branch}, base {baseline?.baseCommit}</p><ul className="mt-2 space-y-2">{members.data?.map((member) => <li key={member.id} className="rounded border p-3 text-sm"><label className="flex gap-2"><input aria-label={`Select ${member.packageId}`} type="checkbox" disabled={member.state !== "prepared"} checked={selected.includes(member.id)} onChange={(e) => setSelected((ids) => e.target.checked ? [...ids, member.id] : ids.filter((id) => id !== member.id))} /><span><b>{member.packageId}</b> · {member.state}<span className="block text-muted-foreground">{member.repoTarget} @ {member.branch} · {member.baseCommit}</span></span></label>{member.state === "prepared" ? <Button className="mt-2" size="xs" variant="outline" type="button" onClick={() => cancel.mutate(member.id)}>Cancel preparation</Button> : null}</li>)}</ul></> : <p className="mt-2 text-sm text-muted-foreground">No prepared members. Eligibility blockers are returned by the server when preparation is attempted.</p>}
    <div className="mt-5 rounded border p-4"><h3 className="font-medium">Immutable dispatch handoff</h3><p className="mt-1 text-sm text-muted-foreground">Select at least two members. Relay creates the exact dispatch; this workspace performs no merge and does not stop or replace the audit journey.</p><Button className="mt-3" type="button" disabled={selected.length < 2 || create.isPending} onClick={() => create.mutate()}>Create immutable dispatch</Button></div>
    {dispatch ? <DispatchView workspaceId={workspaceId} dispatch={dispatch} results={results} setResults={setResults} risks={risks} setRisks={setRisks} valid={Boolean(valid)} onRead={() => read.mutate()} onRecord={() => record.mutate()} assignments={assignments} eligibleCandidates={eligibleCandidates} integrationSelection={integrationSelection} setIntegrationSelection={setIntegrationSelection} mergeResults={mergeResults} verifications={verifications} failures={failures} mergeForms={mergeForms} copyStates={copyStates} integrationMessage={integrationMessage} setMergeRow={setMergeRow} setMergeField={setMergeField} onGenerate={(ids) => generate.mutate(ids)} onCopy={copyAssignment} onReadAssignment={(id) => readAssignment.mutate(id)} onAdmit={(id) => admit.mutate(id)} onVerify={(id) => verify.mutate(id)} onReadFailure={(id) => readFailure.mutate(id)} /> : null}</section>;
}

function DispatchView({ workspaceId, dispatch, results, setResults, risks, setRisks, valid, onRead, onRecord, assignments, eligibleCandidates, integrationSelection, setIntegrationSelection, mergeResults, verifications, failures, mergeForms, copyStates, integrationMessage, setMergeRow, setMergeField, onGenerate, onCopy, onReadAssignment, onAdmit, onVerify, onReadFailure }: { workspaceId: string; dispatch: ProgramDispatch; results: Record<string, Result>; setResults: React.Dispatch<React.SetStateAction<Record<string, Result>>>; risks: string; setRisks: (value: string) => void; valid: boolean; onRead: () => void; onRecord: () => void; assignments: ProgramIntegrationAssignment[]; eligibleCandidates: ProgramDispatch["members"]; integrationSelection: string[]; setIntegrationSelection: React.Dispatch<React.SetStateAction<string[]>>; mergeResults: Record<string, ProgramIntegrationMergeResult | null>; verifications: Record<string, ProgramIntegrationVerification | null>; failures: Record<string, ProgramIntegrationFailure | null>; mergeForms: Record<string, MergeForm>; copyStates: Record<string, CopyStatus>; integrationMessage: string | null; setMergeRow: (assignmentId: string, rowKey: string, patch: Partial<MergeRow>) => void; setMergeField: (assignmentId: string, field: "integratedCommit" | "preservationIdentity" | "conflictEvidence" | "conflictResolution", value: string) => void; onGenerate: (memberIds: string[]) => void; onCopy: (assignment: ProgramIntegrationAssignment) => void; onReadAssignment: (assignmentId: string) => void; onAdmit: (assignmentId: string) => void; onVerify: (assignmentId: string) => void; onReadFailure: (assignmentId: string) => void }) {
  const [handoffStatus, setHandoffStatus] = React.useState<"idle" | "copying" | "copied" | "failed">("idle");
  const copy = () => { setHandoffStatus("copying"); void getProgramHandoff(workspaceId, dispatch.id).then(async ({ text }) => { await navigator.clipboard?.writeText(text); setHandoffStatus("copied"); }).catch(() => setHandoffStatus("failed")); };
  const verified = assignments.filter((a) => a.status === "verified");
  return <div className="mt-5 rounded border p-4">
    <h3 className="font-medium">Dispatch {dispatch.id}</h3>
    <p className="mt-1 text-sm text-muted-foreground">Immutable baseline: {dispatch.repoTarget} @ {dispatch.branch}, base {dispatch.baseCommit} · {dispatch.status}</p>
    <div className="mt-3 flex gap-2"><Button size="sm" variant="outline" type="button" disabled={handoffStatus === "copying"} onClick={copy}>Copy Program handoff</Button>{handoffStatus === "copied" ? <span className="text-sm text-muted-foreground" role="status">Complete Program Orchestrator handoff copied.</span> : null}{handoffStatus === "failed" ? <span className="text-sm text-destructive" role="alert">Handoff export failed; retry from a fresh read.</span> : null}<Button size="sm" variant="outline" type="button" onClick={onRead}>Read dispatch</Button></div>
    {dispatch.status === "reported" ? <>
      <p className="mt-4 text-sm font-medium">Terminal result recorded.</p>
      <ul className="mt-2 text-sm">{dispatch.members.map((m) => <li key={m.id}>{m.packageId}: {m.outcome}{m.outcome === "done" && m.resultBranch ? ` · ${m.resultBranch}` : ""}{m.outcome === "done" && m.branchHeadSha ? ` · ${m.branchHeadSha}` : ""}{m.blocker ? ` · ${m.blocker}` : ""}</li>)}</ul>
      <p className="mt-2 text-sm">Later integration risks: {dispatch.laterIntegrationRisks || "None recorded."}</p>
      <div className="mt-5 rounded border p-4"><h4 className="font-medium">Integration Assignments</h4><p className="mt-1 text-sm text-muted-foreground">Accepted Program-bound constituents with recorded isolated-audit eligibility are integrated through exact immutable Assignments. Relay owns combined validation and verification; this workspace only records the returned Merge result and outcome evidence.</p>{integrationMessage ? <p role="alert" className="mt-3 text-sm text-destructive">{integrationMessage}</p> : null}
        {eligibleCandidates.length ? <div className="mt-3"><p className="text-sm font-medium">Accepted constituents eligible for integration</p><p className="mt-1 text-sm text-muted-foreground">Each accepted constituent is an isolated audit that is eligible only; no completed outcome is recorded until Relay verifies the integrated result.</p><ul className="mt-2 space-y-2">{eligibleCandidates.map((m) => <li key={m.id} className="rounded border p-3 text-sm"><label className="flex gap-2"><input aria-label={`Integrate ${m.packageId}`} type="checkbox" checked={integrationSelection.includes(m.id)} onChange={(e) => setIntegrationSelection((ids) => e.target.checked ? [...ids, m.id] : ids.filter((id) => id !== m.id))} /><span><b>{m.packageId}</b> · accepted · {m.resultBranch}{m.branchHeadSha ? ` · ${m.branchHeadSha}` : ""}<span className="block text-muted-foreground">{m.repoTarget} @ {m.branch} · base {m.baseCommit}</span></span></label></li>)}</ul><Button className="mt-3" size="sm" type="button" disabled={integrationSelection.length === 0} onClick={() => onGenerate(integrationSelection)}>Generate Integration Assignment</Button><p className="mt-2 text-sm text-muted-foreground">Relay re-verifies every exact recorded eligibility fact and emits the immutable Assignment; subset blockers are returned by the server.</p></div> : <p className="mt-3 text-sm text-muted-foreground">No accepted constituents remain eligible: every bound constituent either completed integration through Relay verification or is bound by a current Assignment.</p>}
        {assignments.map((assignment) => <AssignmentCard key={assignment.assignmentId} assignment={assignment} mergeResult={mergeResults[assignment.assignmentId] ?? null} verification={verifications[assignment.assignmentId] ?? null} failure={failures[assignment.assignmentId] ?? null} form={mergeForms[assignment.assignmentId]} copyStatus={copyStates[assignment.assignmentId] ?? "idle"} setMergeRow={setMergeRow} setMergeField={setMergeField} onCopy={() => onCopy(assignment)} onReadAssignment={() => onReadAssignment(assignment.assignmentId)} onAdmit={() => onAdmit(assignment.assignmentId)} onVerify={() => onVerify(assignment.assignmentId)} onReadFailure={() => onReadFailure(assignment.assignmentId)} onFreshAssignment={() => onGenerate(assignment.document.constituents.map((c) => c.memberId))} />)}
        {verified.length ? <div className="mt-4 rounded border border-[var(--relay-row-border)] p-3"><p className="text-sm font-medium">Integrated completed</p><p className="mt-1 text-sm text-muted-foreground">Ordinary completed outcome was recorded by Relay verification only; no completion exists from isolated acceptance.</p><ul className="mt-2 space-y-1 text-sm">{verified.flatMap((a) => a.document.constituents.map((c) => <li key={a.assignmentId + c.memberId}>{c.ticketId} rev {c.ticketRevision} · {c.memberId} · {c.pushedBranch} — completed</li>))}</ul></div> : null}
      </div>
    </> : <div className="mt-4 space-y-3"><h4 className="font-medium">Record terminal member results</h4>{dispatch.members.map((m) => { const r = results[m.id] ?? emptyResult(); const set = (patch: Partial<Result>) => setResults((all) => ({ ...all, [m.id]: { ...r, ...patch } })); const setOutcome = (outcome: Result["outcome"]) => setResults((all) => ({ ...all, [m.id]: outcome === "done" ? { ...r, outcome, blocker: "" } : { ...r, outcome, branch: "", branchHeadSha: "" } })); return <fieldset key={m.id} className="rounded border p-3"><legend className="px-1 text-sm font-medium">{m.packageId}</legend><label className="mr-4 text-sm"><input type="radio" name={m.id} checked={r.outcome === "done"} onChange={() => setOutcome("done")} /> Done</label><label className="text-sm"><input type="radio" name={m.id} checked={r.outcome === "blocked"} onChange={() => setOutcome("blocked")} /> Blocked</label>{r.outcome === "done" ? <><input aria-label={`Branch for ${m.packageId}`} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="Result branch" value={r.branch} onChange={(e) => set({ branch: e.target.value })} /><input aria-label={`Branch head SHA for ${m.packageId}`} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="40-character commit SHA" value={r.branchHeadSha} onChange={(e) => set({ branchHeadSha: e.target.value })} /></> : <input aria-label={`Blocker for ${m.packageId}`} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="Blocking reason" value={r.blocker} onChange={(e) => set({ blocker: e.target.value })} />}</fieldset>; })}<label className="block text-sm">Later integration risks<textarea className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" value={risks} onChange={(e) => setRisks(e.target.value)} /></label><Button type="button" disabled={!valid} onClick={onRecord}>Record terminal results</Button></div>}
  </div>;
}

function AssignmentCard({ assignment, mergeResult, verification, failure, form, copyStatus, setMergeRow, setMergeField, onCopy, onReadAssignment, onAdmit, onVerify, onReadFailure, onFreshAssignment }: { assignment: ProgramIntegrationAssignment; mergeResult: ProgramIntegrationMergeResult | null; verification: ProgramIntegrationVerification | null; failure: ProgramIntegrationFailure | null; form: MergeForm | undefined; copyStatus: CopyStatus; setMergeRow: (assignmentId: string, rowKey: string, patch: Partial<MergeRow>) => void; setMergeField: (assignmentId: string, field: "integratedCommit" | "preservationIdentity" | "conflictEvidence" | "conflictResolution", value: string) => void; onCopy: () => void; onReadAssignment: () => void; onAdmit: () => void; onVerify: () => void; onReadFailure: () => void; onFreshAssignment: () => void }) {
  const id = assignment.assignmentId;
  return <div className="mt-4 rounded border border-[var(--relay-row-border)] p-4" data-assignment-id={id}>
    <h5 className="font-medium">Assignment {id}</h5>
    <p className="mt-1 text-sm text-muted-foreground">Status: {assignment.status} · Verification: {verification ? verification.outcome : "none"} · Content SHA-256: {assignment.contentSha256}</p>
    <ul className="mt-2 space-y-1 text-sm">{assignment.document.constituents.map((c) => <li key={c.memberId}><b>{c.packageId}</b> · {c.ticketId} rev {c.ticketRevision} · accepted {c.acceptedCommit} @ {c.pushedBranch}</li>)}</ul>
    <div className="mt-3 flex gap-2"><Button size="sm" variant="outline" type="button" disabled={copyStatus === "copying"} onClick={onCopy}>Copy exact Assignment</Button>{copyStatus === "copied" ? <span className="text-sm text-muted-foreground" role="status">Exact Assignment copied.</span> : null}{copyStatus === "failed" ? <span className="text-sm text-destructive" role="alert">Assignment export failed; retry from a fresh read.</span> : null}<Button size="sm" variant="outline" type="button" onClick={onReadAssignment}>Read Assignment</Button></div>
    <p className="mt-3 text-sm">Combined validation (Relay-owned, exact):</p><ul className="mt-1 list-disc pl-5 text-sm">{assignment.document.combinedValidation.map((v) => <li key={v.sequence}>{v.command} — expected: {v.expected}</li>)}</ul>
    <p className="mt-2 text-sm">Required evidence:</p><ul className="mt-1 list-disc pl-5 text-sm">{assignment.document.requiredEvidence.map((v) => <li key={v.sequence}>{v.kind} — {v.obligation}</li>)}</ul>
    {assignment.status === "generated" ? <>
      <p className="mt-3 text-sm font-medium">Record the returned Merge result</p><p className="mt-1 text-sm text-muted-foreground">Run the Merge externally against this exact Assignment, then record the exact returned result and evidence below. The outcome identities are bound by the Assignment; only status and evidence are entered here.</p>
      <div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-sm">Integrated commit SHA<input aria-label="Integrated commit SHA" className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="40-character commit SHA" value={form?.integratedCommit ?? ""} onChange={(e) => setMergeField(id, "integratedCommit", e.target.value)} /></label><label className="text-sm">Preservation identity<input aria-label="Preservation identity" className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" value={form?.preservationIdentity ?? ""} onChange={(e) => setMergeField(id, "preservationIdentity", e.target.value)} /></label></div>
      <label className="mt-2 block text-sm">Conflict resolution<select aria-label="Conflict resolution" className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" value={form?.conflictResolution ?? "clean"} onChange={(e) => setMergeField(id, "conflictResolution", e.target.value)}><option value="clean">Clean integration</option><option value="mechanically_resolved">Mechanically resolved</option><option value="material_conflict">Material conflict</option></select></label>
      <label className="mt-2 block text-sm">Conflict evidence{form?.conflictResolution === "mechanically_resolved" ? " (canonical factual JSON)" : " (optional for material conflict)"}<textarea aria-label="Conflict evidence" className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" value={form?.conflictEvidence ?? ""} onChange={(e) => setMergeField(id, "conflictEvidence", e.target.value)} /></label>
      <ul className="mt-3 space-y-2">{assignment.document.combinedValidation.map((v) => { const row = form?.rows[`v:${v.sequence}`]; return <li key={v.sequence} className="rounded border p-3 text-sm"><p className="font-medium">{v.command}</p><p className="text-muted-foreground">Expected: {v.expected}</p><label className="mr-3 text-sm"><input type="radio" name={`validation-${id}-${v.sequence}`} checked={row?.status === "passed"} onChange={() => setMergeRow(id, `v:${v.sequence}`, { status: "passed" })} /> Passed</label><label className="text-sm"><input type="radio" name={`validation-${id}-${v.sequence}`} checked={row?.status === "failed"} onChange={() => setMergeRow(id, `v:${v.sequence}`, { status: "failed" })} /> Failed</label><input aria-label={`Evidence for validation ${v.sequence}`} className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="Outcome evidence" value={row?.evidence ?? ""} onChange={(e) => setMergeRow(id, `v:${v.sequence}`, { evidence: e.target.value })} /></li>; })}</ul>
      <ul className="mt-2 space-y-2">{assignment.document.requiredEvidence.map((v) => { const row = form?.rows[`e:${v.sequence}`]; return <li key={v.sequence} className="rounded border p-3 text-sm"><p className="font-medium">{v.kind}</p><p className="text-muted-foreground">Obligation: {v.obligation}</p><label className="mr-3 text-sm"><input type="radio" name={`evidence-${id}-${v.sequence}`} checked={row?.status === "passed"} onChange={() => setMergeRow(id, `e:${v.sequence}`, { status: "passed" })} /> Passed</label><label className="text-sm"><input type="radio" name={`evidence-${id}-${v.sequence}`} checked={row?.status === "failed"} onChange={() => setMergeRow(id, `e:${v.sequence}`, { status: "failed" })} /> Failed</label><input aria-label={`Evidence for evidence ${v.sequence}`} className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="Outcome evidence" value={row?.evidence ?? ""} onChange={(e) => setMergeRow(id, `e:${v.sequence}`, { evidence: e.target.value })} /></li>; })}</ul>
      <Button className="mt-3" size="sm" type="button" disabled={!form || !mergeFormValid(assignment, form)} onClick={onAdmit}>Record Merge result</Button>
      <p className="mt-2 text-sm text-muted-foreground">Next action: run the Merge against the Assignment and record the exact returned result here.</p>
    </> : null}
    {mergeResult ? <div className="mt-3 rounded border p-3 text-sm"><p className="font-medium">Merge result recorded</p><p className="mt-1 text-muted-foreground">Integrated commit {mergeResult.integratedCommit} · {mergeResult.preservationIdentity}{mergeResult.conflictEvidence ? ` · conflict: ${mergeResult.conflictEvidence}` : ""}</p><ul className="mt-1 space-y-1">{mergeResult.validations.map((v) => <li key={v.sequence}>Validation {v.sequence}: {v.command} — {v.status}</li>)}{mergeResult.evidence.map((v) => <li key={v.sequence}>Evidence {v.sequence}: {v.kind} — {v.status}</li>)}</ul></div> : null}
    {assignment.status === "admitted" ? <><Button className="mt-3" size="sm" type="button" onClick={onVerify}>Run Relay verification</Button><p className="mt-2 text-sm text-muted-foreground">Next action: Relay verifies the admitted Merge result against the exact bound authority and recorded evidence; it never reruns the combined validation.</p></> : null}
    {verification ? <div className="mt-3 rounded border p-3 text-sm" data-verification={verification.outcome}>{verification.outcome === "passed" ? <><p className="font-medium" role="status">Relay verification passed.</p><p className="mt-1 text-muted-foreground">The ordinary completed outcome of every bound constituent whose Ticket revision is still current was recorded; omitted constituents never advance.</p><ul className="mt-1 space-y-1">{verification.completed.map((c) => <li key={c.memberId}>{c.ticketId} rev {c.ticketRevision} · {c.memberId} — {c.completed ? "completed" : "skipped (stale revision)"}</li>)}</ul></> : <><p className="font-medium" role="alert">Relay verification failed.</p><p className="mt-1">{verification.failureReason || failure?.failureReason || "Verification failed."}</p><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" type="button" onClick={onReadFailure}>Read failure evidence</Button><Button size="sm" type="button" onClick={onFreshAssignment}>Generate fresh Assignment</Button></div><p className="mt-2 text-sm text-muted-foreground">Blocked: the failed Assignment is immutable evidence and is never patched or reused; retry only by generating a fresh Assignment from the recorded facts.</p></>}</div> : null}
  </div>;
}
