import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { RelayApiError } from "@/features/workflow-api";
import { approveTicket, publishTicketRevision, selectTicket, ticketDetailQueryOptions, ticketFrontierQueryOptions, ticketKeys, type TicketSelectionMember } from "@/features/relay-tickets";

const plannerOperation = "planner.ticket_frontier";
const operatorOperation = "local_operator.ticket_workflow";

export function RelayTicketFrontier({ workspaceId }: { workspaceId: string }) {
  const queryClient = useQueryClient();
  const [packetId, setPacketId] = React.useState("");
  const [operatorPacketId, setOperatorPacketId] = React.useState("");
  const [operationId, setOperationId] = React.useState(plannerOperation);
  const [selected, setSelected] = React.useState<TicketSelectionMember | null>(null);
  const [rationale, setRationale] = React.useState("Reserve the compatible approved frontier.");
  const [message, setMessage] = React.useState<string | null>(null);
  const [publishTicketId, setPublishTicketId] = React.useState("");
  const [publishSourceClosure, setPublishSourceClosure] = React.useState("");
  const [publishBaseCommit, setPublishBaseCommit] = React.useState("");
  const [publishSourcePath, setPublishSourcePath] = React.useState("");
  const [publishGoal, setPublishGoal] = React.useState("");
  const [publishContext, setPublishContext] = React.useState("");
  const [authorityRevisionId, setAuthorityRevisionId] = React.useState("");
  const [publishCanonical, setPublishCanonical] = React.useState('{"ticket":""}');
  const [publishMarkdown, setPublishMarkdown] = React.useState("# Delivery Ticket\n");
  const frontierQuery = useQuery(ticketFrontierQueryOptions(workspaceId, packetId, operationId));
  const detailQuery = useQuery(ticketDetailQueryOptions(selected?.ticketId ?? ""));
  const report = (error: unknown) => setMessage(error instanceof RelayApiError ? error.message : error instanceof Error ? error.message : "Ticket operation failed.");
  const selectionMutation = useMutation({ mutationFn: () => { if (!selected) throw new Error("Select a ticket first."); return selectTicket(workspaceId, { packetId: operatorPacketId, operationId: operatorOperation, ticketId: selected.ticketId, revisionRowId: selected.revisionRowId, rationale: rationale.trim() }); }, onSuccess: () => { setSelected(null); setMessage("Selection reserved. The selected ticket is no longer on the ready frontier."); void queryClient.invalidateQueries({ queryKey: ticketKeys.all }); }, onError: report });
  const publishMutation = useMutation({ mutationFn: () => { let canonicalJson: unknown; try { canonicalJson = JSON.parse(publishCanonical); } catch { throw new Error("Canonical JSON must be valid JSON."); } return publishTicketRevision(workspaceId, publishTicketId.trim(), { packetId: operatorPacketId, operationId: operatorOperation, externalPriority: 0, expectedRevisionNumber: 0, revision: { repoTarget: "relay", branch: "main", baseCommit: publishBaseCommit.trim(), sourceClosureRowId: Number(publishSourceClosure), sourcePath: publishSourcePath.trim(), goal: publishGoal.trim(), context: publishContext.trim(), transitionApplicability: "not_required", canonicalJson, renderedMarkdown: publishMarkdown, members: [], dependencies: [] } }); }, onSuccess: () => { setMessage("Ticket revision uploaded. Readiness remains derived by the shared owner."); void queryClient.invalidateQueries({ queryKey: ticketKeys.all }); }, onError: report });
  const approvalMutation = useMutation({ mutationFn: () => { const detail = detailQuery.data; if (!detail?.revision) throw new Error("Select a current revision before approving."); return approveTicket(detail.ticketId, { packetId: operatorPacketId, operationId: operatorOperation, revisionRowId: detail.revision.rowId, authorityRevisionId: authorityRevisionId.trim(), sourceClosureRowId: detail.revision.sourceClosureRowId, rationale: "Approved against the displayed current revision." }); }, onSuccess: () => { setMessage("Approval submitted against the displayed revision."); void queryClient.invalidateQueries({ queryKey: ticketKeys.all }); }, onError: report });

  return <main className="space-y-6">
    <section className="rounded border border-[var(--relay-row-border)] bg-[var(--relay-panel-bg)] p-6"><h1 className="text-xl font-semibold">Delivery Ticket frontier</h1><p className="mt-1 text-sm text-muted-foreground">Only the shared ticket owner determines readiness, ordering, tie reasons, and conflicts. This surface cannot create a package or Run.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><Label htmlFor="frontier-packet">Planner packet ID</Label><Input id="frontier-packet" value={packetId} onChange={(event) => setPacketId(event.target.value)} placeholder="Packet admission evidence" /></div><div><Label htmlFor="frontier-operation">Operation</Label><select id="frontier-operation" className="mt-1 w-full rounded border bg-background p-2" value={operationId} onChange={(event) => setOperationId(event.target.value)}><option value={plannerOperation}>{plannerOperation}</option></select></div><div className="sm:col-span-2"><Label htmlFor="operator-packet">Local-operator packet ID</Label><Input id="operator-packet" value={operatorPacketId} onChange={(event) => setOperatorPacketId(event.target.value)} placeholder="Required for publication, approval, and selection" /></div></div>{message ? <p role="alert" className="mt-3 rounded border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{message}</p> : null}</section>
    <section className="rounded border border-[var(--relay-row-border)] bg-[var(--relay-panel-bg)] p-6"><div className="flex items-center justify-between"><h2 className="font-semibold">Ready tickets</h2><span className="text-sm text-muted-foreground">{frontierQuery.data?.entries.length ?? 0} ready</span></div>{frontierQuery.isLoading ? <p className="mt-3 text-sm text-muted-foreground">Waiting for packet-admitted frontier…</p> : frontierQuery.error ? <p role="alert" className="mt-3 text-sm text-destructive">{frontierQuery.error.message}</p> : <div className="mt-3 space-y-2">{frontierQuery.data?.entries.map((entry) => <label key={entry.ticketId} className="block rounded border p-3"><div className="flex items-start gap-3"><input type="radio" name="ticket-selection" checked={selected?.ticketId === entry.ticketId && selected?.revisionRowId === entry.revisionRowId} onChange={() => setSelected({ ticketId: entry.ticketId, revisionRowId: entry.revisionRowId })} /><span className="min-w-0 flex-1"><span className="font-medium">{entry.ticketId}</span><span className="ml-2 text-sm text-muted-foreground">priority {entry.externalPriority} · revision {entry.revisionNumber}</span>{entry.tieWithPrevious ? <span className="mt-1 block text-xs text-muted-foreground">Tie with {entry.tieWithPrevious.previousTicketId}: {entry.tieWithPrevious.rule}</span> : null}</span></div></label>)}</div>}{selected ? <form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); selectionMutation.mutate(); }}><div><Label htmlFor="selection-rationale">Selection rationale</Label><Input id="selection-rationale" value={rationale} onChange={(event) => setRationale(event.target.value)} required /></div><Button type="submit" disabled={selectionMutation.isPending || !operatorPacketId.trim()}>Reserve selected ticket</Button></form> : null}</section>
    {detailQuery.data ? <section className="rounded border border-[var(--relay-row-border)] bg-[var(--relay-panel-bg)] p-6"><h2 className="font-semibold">Current revision and approval basis</h2><p className="mt-2 text-sm">{detailQuery.data.ticketId}: revision {detailQuery.data.revision?.number ?? "none"}</p><p className="mt-1 text-sm text-muted-foreground">{detailQuery.data.readiness.ready ? "Ready" : `Not ready: ${detailQuery.data.readiness.reasons.join(", ") || "currentness checks pending"}`}</p>{detailQuery.data.revision?.approvals.map((approval) => <div key={approval.approvalId} className="mt-3 rounded border p-3 text-sm">Approval {approval.approvalId}: {approval.state}; authority {approval.authorityRevisionId ?? "missing"}; source closure {approval.sourceClosureRowId}</div>)}<div className="mt-3"><Label htmlFor="authority-revision">Current authority revision ID</Label><Input id="authority-revision" value={authorityRevisionId} onChange={(event) => setAuthorityRevisionId(event.target.value)} required /></div><Button className="mt-4" type="button" disabled={approvalMutation.isPending || !operatorPacketId.trim() || !authorityRevisionId.trim() || !detailQuery.data.revision} onClick={() => approvalMutation.mutate()}>Approve displayed revision</Button><p className="mt-3 text-xs text-muted-foreground">History entries: {detailQuery.data.history.length}. Approval is bound to this exact revision, source closure, and current authority.</p></section> : null}
    <section className="rounded border border-[var(--relay-row-border)] bg-[var(--relay-panel-bg)] p-6"><h2 className="font-semibold">Upload a ticket revision</h2><p className="mt-1 text-sm text-muted-foreground">The packet-admitted owner validates all fields and derives readiness after publication.</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); publishMutation.mutate(); }}><div><Label htmlFor="publish-ticket">Ticket ID</Label><Input id="publish-ticket" value={publishTicketId} onChange={(event) => setPublishTicketId(event.target.value)} required /></div><div><Label htmlFor="publish-source">Source closure row ID</Label><Input id="publish-source" inputMode="numeric" value={publishSourceClosure} onChange={(event) => setPublishSourceClosure(event.target.value)} required /></div><div><Label htmlFor="publish-base">Base commit</Label><Input id="publish-base" value={publishBaseCommit} onChange={(event) => setPublishBaseCommit(event.target.value)} required /></div><div><Label htmlFor="publish-path">Source path</Label><Input id="publish-path" value={publishSourcePath} onChange={(event) => setPublishSourcePath(event.target.value)} required /></div><div><Label htmlFor="publish-goal">Goal</Label><Input id="publish-goal" value={publishGoal} onChange={(event) => setPublishGoal(event.target.value)} required /></div><div><Label htmlFor="publish-context">Context</Label><Input id="publish-context" value={publishContext} onChange={(event) => setPublishContext(event.target.value)} required /></div><div className="sm:col-span-2"><Label htmlFor="publish-canonical">Canonical JSON</Label><Textarea id="publish-canonical" value={publishCanonical} onChange={(event) => setPublishCanonical(event.target.value)} required /></div><div className="sm:col-span-2"><Label htmlFor="publish-rendered">Rendered Markdown</Label><Textarea id="publish-rendered" value={publishMarkdown} onChange={(event) => setPublishMarkdown(event.target.value)} required /></div><Button type="submit" disabled={publishMutation.isPending || !operatorPacketId.trim()}>Upload revision</Button></form></section>
  </main>;
}
