import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { cancelProgramMember, createProgramDispatch, getProgramDispatch, listProgramMembers, prepareProgramMember, recordProgramDispatchResult, type ProgramDispatch } from "@/features/relay-programs";

const key = (workspaceId: string) => ["feature-workspaces", workspaceId, "program-members"] as const;
type Result = { outcome: "done" | "blocked"; branch: string; branchHeadSha: string; blocker: string };
const error = (value: unknown) => value instanceof Error ? value.message : "Program workspace action failed.";
const emptyResult = (): Result => ({ outcome: "done", branch: "", branchHeadSha: "", blocker: "" });
const normalizedResult = (memberId: string, result: Result) => result.outcome === "done" ? { memberId, outcome: result.outcome, branch: result.branch.trim(), branchHeadSha: result.branchHeadSha.trim().toLowerCase(), blocker: "" } : { memberId, outcome: result.outcome, branch: "", branchHeadSha: "", blocker: result.blocker.trim() };

export function RelayFeatureWorkspaceProgram({ workspaceId, expectedVersion }: { workspaceId: string; expectedVersion: number }) {
  const client = useQueryClient(); const [packageId, setPackageId] = React.useState(""); const [selected, setSelected] = React.useState<string[]>([]); const [dispatch, setDispatch] = React.useState<ProgramDispatch | null>(null); const [results, setResults] = React.useState<Record<string, Result>>({}); const [risks, setRisks] = React.useState(""); const [message, setMessage] = React.useState<string | null>(null);
  const members = useQuery({ queryKey: key(workspaceId), queryFn: () => listProgramMembers(workspaceId), staleTime: 5_000 }); const refresh = () => client.invalidateQueries({ queryKey: key(workspaceId) });
  const prepare = useMutation({ mutationFn: () => prepareProgramMember(workspaceId, { packageId: packageId.trim(), expectedVersion }), onSuccess: () => { setPackageId(""); setMessage(null); void refresh(); }, onError: (e) => setMessage(error(e)) });
  const cancel = useMutation({ mutationFn: (id: string) => cancelProgramMember(workspaceId, id, expectedVersion), onSuccess: () => { setSelected([]); void refresh(); }, onError: (e) => setMessage(error(e)) });
  const create = useMutation({ mutationFn: () => createProgramDispatch(workspaceId, { expectedVersion, memberIds: selected }), onSuccess: (value) => { setDispatch(value); setSelected([]); setResults({}); setRisks(""); void refresh(); }, onError: (e) => setMessage(error(e)) });
  const read = useMutation({ mutationFn: () => dispatch ? getProgramDispatch(workspaceId, dispatch.id) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: setDispatch, onError: (e) => setMessage(error(e)) });
  const record = useMutation({ mutationFn: () => dispatch ? recordProgramDispatchResult(workspaceId, dispatch.id, { expectedVersion, laterIntegrationRisks: risks, members: dispatch.members.map((member) => normalizedResult(member.id, results[member.id] ?? emptyResult())) }) : Promise.reject(new Error("Create a dispatch first.")), onSuccess: () => void read.mutateAsync(), onError: (e) => setMessage(error(e)) });
  const prepared = members.data?.filter((member) => member.state === "prepared") ?? []; const baseline = prepared[0]; const valid = dispatch?.status === "dispatched" && dispatch.members.every((member) => { const result = normalizedResult(member.id, results[member.id] ?? emptyResult()); return result.outcome === "done" ? result.branch.length > 0 && /^[0-9a-f]{40}$/.test(result.branchHeadSha) : result.blocker.length > 0; });
  return <section aria-labelledby="program-workspace" className="rounded border border-[var(--relay-row-border)] bg-[var(--relay-panel-bg)] p-6"><h2 id="program-workspace" className="font-semibold">Program workspace</h2><p className="mt-1 text-sm text-muted-foreground">Prepare one eligible approved current package at a time. Members require a common repository, branch, and base commit before immutable handoff to the external Program Orchestrator.</p>{message ? <p role="alert" className="mt-3 text-sm text-destructive">{message}</p> : null}
    <form className="mt-4 flex gap-2" onSubmit={(e) => { e.preventDefault(); prepare.mutate(); }}><label className="sr-only" htmlFor="program-package">Approved package ID</label><input id="program-package" className="rounded border bg-background px-3 py-2 text-sm" placeholder="Approved package ID" value={packageId} onChange={(e) => setPackageId(e.target.value)} /><Button type="submit" disabled={!packageId.trim() || prepare.isPending}>Prepare package</Button></form>
    <h3 className="mt-5 font-medium">Prepared members</h3>{members.isLoading ? <p className="mt-2 text-sm">Loading prepared members…</p> : prepared.length ? <><p className="mt-2 text-sm text-muted-foreground">Common baseline: {baseline?.repoTarget} @ {baseline?.branch}, base {baseline?.baseCommit}</p><ul className="mt-2 space-y-2">{members.data?.map((member) => <li key={member.id} className="rounded border p-3 text-sm"><label className="flex gap-2"><input aria-label={`Select ${member.packageId}`} type="checkbox" disabled={member.state !== "prepared"} checked={selected.includes(member.id)} onChange={(e) => setSelected((ids) => e.target.checked ? [...ids, member.id] : ids.filter((id) => id !== member.id))} /><span><b>{member.packageId}</b> · {member.state}<span className="block text-muted-foreground">{member.repoTarget} @ {member.branch} · {member.baseCommit}</span></span></label>{member.state === "prepared" ? <Button className="mt-2" size="xs" variant="outline" type="button" onClick={() => cancel.mutate(member.id)}>Cancel preparation</Button> : null}</li>)}</ul></> : <p className="mt-2 text-sm text-muted-foreground">No prepared members. Eligibility blockers are returned by the server when preparation is attempted.</p>}
    <div className="mt-5 rounded border p-4"><h3 className="font-medium">Immutable dispatch handoff</h3><p className="mt-1 text-sm text-muted-foreground">Select at least two members. Relay creates the exact dispatch; this workspace performs no merge and does not stop or replace the audit journey.</p><Button className="mt-3" type="button" disabled={selected.length < 2 || create.isPending} onClick={() => create.mutate()}>Create immutable dispatch</Button></div>
    {dispatch ? <DispatchView dispatch={dispatch} results={results} setResults={setResults} risks={risks} setRisks={setRisks} valid={Boolean(valid)} onRead={() => read.mutate()} onRecord={() => record.mutate()} /> : null}</section>;
}

function DispatchView({ dispatch, results, setResults, risks, setRisks, valid, onRead, onRecord }: { dispatch: ProgramDispatch; results: Record<string, Result>; setResults: React.Dispatch<React.SetStateAction<Record<string, Result>>>; risks: string; setRisks: (value: string) => void; valid: boolean; onRead: () => void; onRecord: () => void }) {
  const copy = () => void navigator.clipboard?.writeText(dispatch.id); return <div className="mt-5 rounded border p-4"><h3 className="font-medium">Dispatch {dispatch.id}</h3><p className="mt-1 text-sm text-muted-foreground">Immutable baseline: {dispatch.repoTarget} @ {dispatch.branch}, base {dispatch.baseCommit} · {dispatch.status}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" type="button" onClick={copy}>Copy dispatch ID</Button><Button size="sm" variant="outline" type="button" onClick={onRead}>Read dispatch</Button></div>{dispatch.status === "reported" ? <><p className="mt-4 text-sm font-medium">Terminal result recorded.</p><ul className="mt-2 text-sm">{dispatch.members.map((m) => <li key={m.id}>{m.packageId}: {m.outcome}{m.outcome === "done" && m.resultBranch ? ` · ${m.resultBranch}` : ""}{m.outcome === "done" && m.branchHeadSha ? ` · ${m.branchHeadSha}` : ""}{m.blocker ? ` · ${m.blocker}` : ""}</li>)}</ul><p className="mt-2 text-sm">Later integration risks: {dispatch.laterIntegrationRisks || "None recorded."}</p></> : <div className="mt-4 space-y-3"><h4 className="font-medium">Record terminal member results</h4>{dispatch.members.map((m) => { const r = results[m.id] ?? emptyResult(); const set = (patch: Partial<Result>) => setResults((all) => ({ ...all, [m.id]: { ...r, ...patch } })); const setOutcome = (outcome: Result["outcome"]) => setResults((all) => ({ ...all, [m.id]: outcome === "done" ? { ...r, outcome, blocker: "" } : { ...r, outcome, branch: "", branchHeadSha: "" } })); return <fieldset key={m.id} className="rounded border p-3"><legend className="px-1 text-sm font-medium">{m.packageId}</legend><label className="mr-4 text-sm"><input type="radio" name={m.id} checked={r.outcome === "done"} onChange={() => setOutcome("done")} /> Done</label><label className="text-sm"><input type="radio" name={m.id} checked={r.outcome === "blocked"} onChange={() => setOutcome("blocked")} /> Blocked</label>{r.outcome === "done" ? <><input aria-label={`Branch for ${m.packageId}`} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="Result branch" value={r.branch} onChange={(e) => set({ branch: e.target.value })} /><input aria-label={`Branch head SHA for ${m.packageId}`} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="40-character commit SHA" value={r.branchHeadSha} onChange={(e) => set({ branchHeadSha: e.target.value })} /></> : <input aria-label={`Blocker for ${m.packageId}`} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm" placeholder="Blocking reason" value={r.blocker} onChange={(e) => set({ blocker: e.target.value })} />}</fieldset>; })}<label className="block text-sm">Later integration risks<textarea className="mt-1 w-full rounded border bg-background px-3 py-2 text-sm" value={risks} onChange={(e) => setRisks(e.target.value)} /></label><Button type="button" disabled={!valid} onClick={onRecord}>Record terminal results</Button></div>}</div>;
}
