#!/usr/bin/env bash
set -euo pipefail

echo "=== Cutover Store & App Tests ==="
go test ./internal/store/workflow/...
go test ./internal/app/cutover/...

echo "=== Admission Gate Tests ==="
go test ./internal/app/submissions/...
go test ./internal/app/plans/workflow/...
go test ./internal/app/runs/workflow/...

echo "=== Operations & Transport Tests ==="
go test ./internal/app/operations/...
go test ./internal/api/cutover/...

echo "=== Server & MCP Tests ==="
go test ./internal/server/...
go test ./internal/mcp/...

echo "=== Database Migration Tests ==="
go test ./internal/db/...

echo "=== Frontend Tests ==="
npm --prefix apps/web test -- --run

echo "=== Frontend Type Check ==="
npm --prefix apps/web run typecheck

echo "=== PASS-7 Verification Complete ==="
