package auditor

import (
	"fmt"
	"strings"
	"time"
)

// GenerateAuditPacket renders a normalized audit packet from structured evidence.
// It never silently uses _Not available_ for required evidence sections.
// Missing evidence produces explicit warnings and audit consequence notes.
func GenerateAuditPacket(ev *Evidence, decision Decision) string {
	var b strings.Builder
	validationResults := sanitizedValidationResults(ev.ValidationResults)

	b.WriteString("# Audit Packet\n\n")

	// --- Metadata ---
	b.WriteString("## Audit Packet Metadata\n\n")
	b.WriteString(fmt.Sprintf("- **Run ID:** %d\n", ev.RunID))
	b.WriteString(fmt.Sprintf("- **Run Title:** %s\n", ev.RunTitle))
	b.WriteString(fmt.Sprintf("- **Packet ID:** %s\n", ev.Packet.PacketID))
	b.WriteString(fmt.Sprintf("- **Generated:** %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("- **Preliminary Decision:** %s\n", string(decision)))
	b.WriteString("- **Evidence manifest artifact:** audit_evidence_manifest.json\n")
	b.WriteString("- **Evidence scope:** Local-only artifacts; GitHub PRs, CI, and Actions are not used.\n")
	b.WriteString("\n")

	b.WriteString("> This audit packet was generated by the Relay audit service.\n")
	b.WriteString("> It does **not** constitute final human acceptance.\n")
	b.WriteString("> A separate explicit approval action is required to accept or close the run.\n\n")

	// --- Scope Review ---
	b.WriteString("## Scope Review\n\n")

	b.WriteString("### Goal\n\n")
	if ev.Packet.Goal != "" {
		b.WriteString(ev.Packet.Goal)
		b.WriteString("\n")
	} else {
		b.WriteString("⚠ **EVIDENCE GAP:** Goal not available from canonical_packet.json.\n")
		b.WriteString("**Audit consequence:** File scope and goal alignment cannot be confirmed. Decision escalated to manual_review_required.\n")
	}
	b.WriteString("\n")

	b.WriteString("### Scope\n\n")
	if ev.Packet.Scope != "" {
		b.WriteString(ev.Packet.Scope)
		b.WriteString("\n")
	} else {
		b.WriteString("⚠ **EVIDENCE GAP:** Scope not available from canonical_packet.json.\n")
		b.WriteString("**Audit consequence:** Scope enforcement cannot proceed. Decision escalated to manual_review_required.\n")
	}
	b.WriteString("\n")

	b.WriteString("### Non-goals\n\n")
	if ev.Packet.NonGoals != "" {
		// Render as bullet list if multi-line
		lines := strings.Split(strings.TrimSpace(ev.Packet.NonGoals), "\n")
		for _, l := range lines {
			l = strings.TrimSpace(l)
			if l != "" {
				if !strings.HasPrefix(l, "-") {
					b.WriteString(fmt.Sprintf("- %s\n", l))
				} else {
					b.WriteString(l + "\n")
				}
			}
		}
	} else {
		b.WriteString("⚠ **EVIDENCE GAP:** Non-goals not available from canonical_packet.json.\n")
		b.WriteString("**Audit consequence:** Non-goal enforcement cannot proceed. Auditor must verify manually.\n")
	}
	b.WriteString("\n")

	// --- Raw Artifact References ---
	b.WriteString("## Raw Artifact References\n\n")
	b.WriteString("| Evidence Section | Artifact Kind | Path |\n")
	b.WriteString("|---|---|---|\n")
	if ev.ExecutorResult.Present {
		b.WriteString(fmt.Sprintf("| Executor Result | `executor_result` | `%s` |\n", ev.ExecutorResult.RawArtifactPath))
	} else {
		b.WriteString("| Executor Result | `executor_result` | ⚠ not present |\n")
	}
	if ev.ChangedFiles.Present {
		b.WriteString(fmt.Sprintf("| Changed Files | `%s` | `%s` |\n", ev.ChangedFiles.SourceKind, ev.ChangedFiles.RawArtifactPath))
	} else {
		b.WriteString("| Changed Files | `git_diff_name_status` / `git_status_text` | ⚠ not present |\n")
	}
	if ev.GitDiff.Present {
		b.WriteString(fmt.Sprintf("| Git Diff Patch | `git_diff_patch` | `%s` |\n", ev.GitDiff.RawArtifactPath))
	} else {
		b.WriteString("| Git Diff Patch | `git_diff_patch` | ⚠ not present |\n")
	}
	for _, vr := range validationResults {
		kind := vr.RawArtifactKind
		if kind == "" {
			kind = "validation_stdout"
		}
		if vr.RawArtifactPath != "" {
			b.WriteString(fmt.Sprintf("| Validation (%s) | `%s` | `%s` |\n", vr.ID, kind, vr.RawArtifactPath))
		} else {
			b.WriteString(fmt.Sprintf("| Validation (%s) | `%s` | ⚠ not present |\n", vr.ID, kind))
		}
	}
	if ev.AcceptanceEvidence.Present {
		b.WriteString(fmt.Sprintf("| Validation Failure Acceptance | `validation_failure_acceptance_json` | `%s` |\n", ev.AcceptanceEvidence.RawArtifactPath))
	}
	b.WriteString("\n")

	// --- Implementation Evidence ---
	b.WriteString("## Implementation Evidence\n\n")
	b.WriteString("### Executor Result\n\n")
	b.WriteString("**Source:** `executor_result.txt` (artifact kind: `executor_result`)\n\n")
	if ev.ExecutorResult.Present {
		if ev.ExecutorResult.Summary != "" {
			b.WriteString("**Status Summary:**\n```\n")
			b.WriteString(ev.ExecutorResult.Summary)
			b.WriteString("\n```\n\n")
		}
		if ev.ExecutorResult.RawArtifactPath != "" {
			b.WriteString(fmt.Sprintf("**Full artifact:** `%s`\n\n", ev.ExecutorResult.RawArtifactPath))
		}
		b.WriteString("**Preview (bounded):**\n```\n")
		b.WriteString(ev.ExecutorResult.Content)
		b.WriteString("\n```\n")
	} else {
		b.WriteString("⚠ **EVIDENCE GAP: Executor result artifact not found.**\n")
		b.WriteString("**Audit consequence:** Executor status, build status, and test status cannot be confirmed. ")
		b.WriteString("Checklist items requiring executor evidence are marked `unknown`.\n")
	}
	b.WriteString("\n")

	// --- Validation Evidence ---
	b.WriteString("## Validation Evidence\n\n")
	if len(validationResults) == 0 {
		b.WriteString("⚠ **EVIDENCE GAP: No validation evidence found.**\n")
		b.WriteString("**Audit consequence:** Validation cannot be confirmed. Required validation checks are marked `unknown`.\n")
	} else {
		b.WriteString("| ID | Command | Required | Status | Exit Result | Evidence Summary | Raw Artifact Path |\n")
		b.WriteString("|---|---|---|---|---|---|---|\n")
		for _, vr := range validationResults {
			req := "no"
			if vr.Required {
				req = "**yes**"
			}
			rawPath := vr.RawArtifactPath
			if rawPath == "" {
				rawPath = "_not available_"
			} else {
				rawPath = fmt.Sprintf("`%s`", rawPath)
			}
			b.WriteString(fmt.Sprintf("| %s | `%s` | %s | `%s` | %s | %s | %s |\n",
				vr.ID, vr.Command, req, string(vr.Status), vr.ExitResult, vr.EvidenceSummary, rawPath))
		}
		b.WriteString("\n")
		for _, vr := range validationResults {
			if vr.RawArtifactPath != "" {
				b.WriteString(fmt.Sprintf("**%s full artifact:** `%s`\n\n", vr.ID, vr.RawArtifactPath))
			}
		}
	}
	b.WriteString("\n")

	if ev.AcceptanceEvidence.Present {
		b.WriteString("## Validation Failure Acceptance\n\n")
		b.WriteString(fmt.Sprintf("**Source:** `%s`\n\n", ev.AcceptanceEvidence.RawArtifactPath))
		b.WriteString("**Content:**\n```json\n")
		b.WriteString(ev.AcceptanceEvidence.Content)
		b.WriteString("\n```\n\n")
	}

	// --- Changed Files ---
	b.WriteString("## Changed Files / Diff Review\n\n")
	b.WriteString("### Implementation Changed Files\n\n")
	if ev.ChangedFiles.Present && len(ev.ChangedFiles.ImplementationFiles) > 0 {
		b.WriteString(fmt.Sprintf("**Source kind:** `%s`\n", ev.ChangedFiles.SourceKind))
		b.WriteString(fmt.Sprintf("**Full artifact:** `%s`\n\n", ev.ChangedFiles.RawArtifactPath))
		b.WriteString("```\n")
		for _, f := range ev.ChangedFiles.ImplementationFiles {
			b.WriteString(fmt.Sprintf("%s\t%s\n", f.Status, f.Path))
		}
		b.WriteString("```\n")
	} else if ev.ChangedFiles.Present {
		b.WriteString("_No implementation/source files changed in this run — only generated pipeline artifacts were modified._\n")
		b.WriteString(fmt.Sprintf("**Full changed-files artifact:** `%s`\n\n", ev.ChangedFiles.RawArtifactPath))
	} else {
		b.WriteString("⚠ **EVIDENCE GAP: Changed files artifact not found.**\n")
		b.WriteString("**Audit consequence:** File scope cannot be confirmed. File-scope checks are marked `unknown`. ")
		b.WriteString("Decision escalated to at least manual_review_required.\n")
	}
	b.WriteString("\n")

	b.WriteString("### Generated Pipeline Artifacts\n\n")
	if len(ev.ChangedFiles.GeneratedArtifactFiles) > 0 {
		b.WriteString("These are generated pipeline artifacts produced during the run, not implementation/source files. They are excluded from file-target enforcement and surfaced here as evidence inputs.\n\n")
		b.WriteString("| Status | Path | Inferred Artifact Kind | Recognized |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, ga := range ev.ChangedFiles.GeneratedArtifactFiles {
			rec := "yes"
			if !ga.Recognized {
				rec = "⚠ no"
			}
			b.WriteString(fmt.Sprintf("| %s | `%s` | `%s` | %s |\n", ga.Status, ga.Path, ga.InferredArtifactKind, rec))
		}
		b.WriteString("\n")
	} else {
		b.WriteString("_No generated pipeline artifacts were changed in this run._\n\n")
	}

	b.WriteString("### Diff Preview\n\n")
	if ev.GitDiff.Present {
		b.WriteString(fmt.Sprintf("**Full patch artifact:** `%s`\n\n", ev.GitDiff.RawArtifactPath))
		b.WriteString("**Bounded preview (first 3000 bytes):**\n")
		b.WriteString("```diff\n")
		b.WriteString(ev.GitDiff.Preview)
		b.WriteString("\n```\n")
	} else {
		b.WriteString("⚠ **EVIDENCE GAP: git_diff.patch artifact not found.**\n")
		b.WriteString("**Audit consequence:** Diff cannot be reviewed inline. Auditor must obtain diff externally if required.\n")
	}
	b.WriteString("\n")

	// --- Expected File Targets ---
	if len(ev.Packet.FileTargets) > 0 {
		b.WriteString("### Expected File Targets\n\n")
		b.WriteString("The following files were expected to change per the packet:\n\n")
		for _, ft := range ev.Packet.FileTargets {
			b.WriteString(fmt.Sprintf("- `%s`\n", ft))
		}
		b.WriteString("\n")
	}

	// --- Audit Checklist Evaluation ---
	b.WriteString("## Audit Checklist Evaluation\n\n")
	if len(ev.ChecklistResults) == 0 {
		b.WriteString("⚠ **EVIDENCE GAP: No checklist items to evaluate.**\n")
		b.WriteString("**Audit consequence:** All checklist evaluation requires manual review.\n")
	} else {
		b.WriteString("| ID | Check | Result | Severity if Failed | Evidence Source | Rationale |\n")
		b.WriteString("|---|---|---|---|---|---|\n")
		for _, cr := range ev.ChecklistResults {
			sev := string(cr.SeverityIfFailed)
			if cr.Result == CheckFail || cr.Result == CheckUnknown {
				sev = fmt.Sprintf("**%s**", sev)
			}
			b.WriteString(fmt.Sprintf("| %s | %s | `%s` | %s | %s | %s |\n",
				cr.ID, cr.Check, string(cr.Result), sev, cr.EvidenceSource, cr.Rationale))
		}
	}
	b.WriteString("\n")

	// --- File Scope Results ---
	b.WriteString("## File Scope Enforcement\n\n")
	if len(ev.FileScopeResults) == 0 {
		b.WriteString("⚠ **EVIDENCE GAP: File scope checks unavailable.**\n")
	} else {
		b.WriteString("| ID | Check | Result | Severity if Failed | Evidence Source | Rationale |\n")
		b.WriteString("|---|---|---|---|---|---|\n")
		for _, cr := range ev.FileScopeResults {
			sev := string(cr.SeverityIfFailed)
			if cr.Result == CheckFail {
				sev = fmt.Sprintf("**%s**", sev)
			}
			b.WriteString(fmt.Sprintf("| %s | %s | `%s` | %s | %s | %s |\n",
				cr.ID, cr.Check, string(cr.Result), sev, cr.EvidenceSource, cr.Rationale))
		}
	}
	b.WriteString("\n")

	// --- Non-goal Results ---
	b.WriteString("## Non-goal Enforcement\n\n")
	if len(ev.NonGoalResults) == 0 {
		b.WriteString("⚠ **EVIDENCE GAP: Non-goal checks unavailable.**\n")
	} else {
		b.WriteString("| ID | Check | Result | Severity if Failed | Evidence Source | Rationale |\n")
		b.WriteString("|---|---|---|---|---|---|\n")
		for _, cr := range ev.NonGoalResults {
			sev := string(cr.SeverityIfFailed)
			b.WriteString(fmt.Sprintf("| %s | %s | `%s` | %s | %s | %s |\n",
				cr.ID, cr.Check, string(cr.Result), sev, cr.EvidenceSource, cr.Rationale))
		}
	}
	b.WriteString("\n")

	// --- Warnings ---
	b.WriteString("## Evidence Warnings\n\n")
	if len(ev.Warnings) == 0 {
		b.WriteString("_No evidence warnings._\n")
	} else {
		b.WriteString("| Severity | Warning |\n")
		b.WriteString("|---|---|\n")
		for _, w := range ev.Warnings {
			b.WriteString(fmt.Sprintf("| `%s` | %s |\n", string(w.Severity), w.Message))
		}
	}
	b.WriteString("\n")

	// --- Revision Requirements ---
	b.WriteString("## Revision Requirements\n\n")
	if len(ev.RevisionRequirements) == 0 {
		b.WriteString("_No specific revision requirements identified from evidence._\n")
	} else {
		for _, rr := range ev.RevisionRequirements {
			b.WriteString(fmt.Sprintf("- [%s] %s\n", string(rr.Severity), rr.Reason))
		}
	}
	b.WriteString("\n")

	// --- Final Decision ---
	b.WriteString("## Final Recommendation\n\n")
	b.WriteString(fmt.Sprintf("**Preliminary Decision:** `%s`\n\n", string(decision)))
	b.WriteString("**Decision Basis:**\n\n")
	switch decision {
	case DecisionAccepted:
		b.WriteString("All required evidence is present and no blocking warnings were found.\n")
	case DecisionAcceptedWithWarnings:
		b.WriteString("Evidence is substantially present but non-blocking warnings or informational notes require auditor awareness. This preliminary recommendation does not constitute final human acceptance.\n")
		if len(ev.Warnings) > 0 {
			b.WriteString("\n**Non-blocking warnings:**\n")
			for _, w := range ev.Warnings {
				if w.Severity == SeverityWarning || w.Severity == SeverityInfo {
					b.WriteString(fmt.Sprintf("- [%s] %s\n", string(w.Severity), w.Message))
				}
			}
		}
	case DecisionManualReviewRequired:
		b.WriteString("One or more evidence sections are missing or show unknown results. ")
		b.WriteString("The auditor must manually verify the following before accepting:\n\n")
		for _, w := range ev.Warnings {
			if w.Severity == SeverityError || w.Severity == SeverityBlocker {
				b.WriteString(fmt.Sprintf("- [%s] %s\n", string(w.Severity), w.Message))
			}
		}
		for _, cr := range ev.FileScopeResults {
			if cr.Result == CheckFail && (cr.SeverityIfFailed == SeverityBlocker || cr.SeverityIfFailed == SeverityError) {
				b.WriteString(fmt.Sprintf("- [file-scope] %s: %s\n", cr.ID, cr.Rationale))
			}
		}
		for _, cr := range ev.ChecklistResults {
			if cr.Result == CheckFail && (cr.SeverityIfFailed == SeverityBlocker || cr.SeverityIfFailed == SeverityError) {
				b.WriteString(fmt.Sprintf("- [checklist] %s (%s): %s\n", cr.ID, cr.Check, cr.Rationale))
			}
		}
		for _, vr := range ev.ValidationResults {
			if vr.Required && vr.Status == CheckFail {
				b.WriteString(fmt.Sprintf("- [validation] %s (%s): %s\n", vr.ID, vr.Command, vr.EvidenceSummary))
			}
		}
	case DecisionRevisionRequired:
		b.WriteString("Evidence shows one or more failures that require the executor to make corrections.\n")
		for _, rr := range ev.RevisionRequirements {
			b.WriteString(fmt.Sprintf("- [%s] %s\n", string(rr.Severity), rr.Reason))
		}
	case DecisionBlocked:
		b.WriteString("Critical evidence is missing or blocking failures were found. ")
		b.WriteString("The run cannot be accepted until blockers are resolved.\n")
		for _, w := range ev.Warnings {
			if w.Severity == SeverityBlocker {
				b.WriteString(fmt.Sprintf("- **BLOCKER:** %s\n", w.Message))
			}
		}
		for _, cr := range ev.FileScopeResults {
			if cr.Result == CheckFail && cr.SeverityIfFailed == SeverityBlocker {
				b.WriteString(fmt.Sprintf("- **BLOCKER:** [file-scope] %s: %s\n", cr.ID, cr.Rationale))
			}
		}
		for _, cr := range ev.ChecklistResults {
			if cr.Result == CheckFail && cr.SeverityIfFailed == SeverityBlocker {
				b.WriteString(fmt.Sprintf("- **BLOCKER:** [checklist] %s (%s): %s\n", cr.ID, cr.Check, cr.Rationale))
			}
		}
	}
	b.WriteString("\n")
	b.WriteString("---\n\n")
	b.WriteString("*Generated by Relay audit service. This packet is not final human acceptance. ")
	b.WriteString("An explicit human approval action is required to accept or close this run.*\n")

	return b.String()
}

func sanitizedValidationResults(results []ValidationCommandResult) []ValidationCommandResult {
	out := make([]ValidationCommandResult, 0, len(results))
	for _, result := range results {
		result.ID = strings.TrimSpace(result.ID)
		result.Command = strings.TrimSpace(result.Command)
		if result.ID == "" || result.ID == "V?" {
			result.ID = fallbackValidationID(result.RawArtifactKind)
		}
		if strings.Contains(result.Command, "unknown - not in packet") ||
			strings.Contains(result.Command, "unknown — not in packet") ||
			result.Command == "" {
			result.Command = fallbackValidationCommand(result.RawArtifactKind)
		}
		out = append(out, result)
	}
	return out
}

func fallbackValidationID(kind string) string {
	if kind == "validation_run_json" {
		return "VAL-RUN"
	}
	return "VAL-ARTIFACT"
}

func fallbackValidationCommand(kind string) string {
	if kind == "validation_run_json" {
		return "validation_run_json artifact status"
	}
	return "validation artifact status"
}

// DetermineDefaultDecision derives a preliminary decision from the collected evidence.
// • Blocker → blocked
// • Concrete failures (validation/checklist/file-scope fails + error) → revision_required
// • Error-severity evidence gaps (missing artifacts, etc.) → manual_review_required
// • Warning-only evidence → accepted_with_warnings
// • No warnings/failures → accepted
// Never marks unknown evidence as pass.
func DetermineDefaultDecision(ev *Evidence) Decision {
	hasBlocker := false
	hasConcreteFailure := false
	hasErrorEvidenceGap := false
	hasWarning := false

	for _, w := range ev.Warnings {
		switch w.Severity {
		case SeverityBlocker:
			hasBlocker = true
		case SeverityError:
			hasErrorEvidenceGap = true
		case SeverityWarning:
			hasWarning = true
		}
	}

	// Check for concrete failures from file scope, checklist, and validation
	for _, cr := range ev.FileScopeResults {
		if cr.Result == CheckFail && (cr.SeverityIfFailed == SeverityBlocker || cr.SeverityIfFailed == SeverityError) {
			hasConcreteFailure = true
		}
	}

	for _, cr := range ev.ChecklistResults {
		if cr.Result == CheckFail {
			switch cr.SeverityIfFailed {
			case SeverityBlocker:
				hasBlocker = true
			case SeverityError:
				hasConcreteFailure = true
			}
		}
	}

	for _, vr := range ev.ValidationResults {
		if vr.Required && vr.Status == CheckFail {
			hasConcreteFailure = true
		}
	}

	switch {
	case hasBlocker:
		return DecisionBlocked
	case hasConcreteFailure:
		return DecisionRevisionRequired
	case hasErrorEvidenceGap:
		return DecisionManualReviewRequired
	case hasWarning:
		return DecisionAcceptedWithWarnings
	case len(ev.Warnings) > 0:
		return DecisionAcceptedWithWarnings
	}

	return DecisionAccepted
}

// flattenWarningMessages converts structured EvidenceWarning to plain strings for the GeneratedAudit response.
func flattenWarningMessages(warnings []EvidenceWarning) []string {
	out := make([]string, len(warnings))
	for i, w := range warnings {
		out[i] = fmt.Sprintf("[%s] %s", string(w.Severity), w.Message)
	}
	return out
}

// flattenRevisionRequirements converts RevisionRequirement to plain strings.
func flattenRevisionRequirements(reqs []RevisionRequirement) []string {
	out := make([]string, len(reqs))
	for i, r := range reqs {
		out[i] = fmt.Sprintf("[%s] %s", string(r.Severity), r.Reason)
	}
	return out
}
