package auditor

import (
	"fmt"
	"strings"
	"time"
)

const auditPacketTemplate = `# Audit Packet

## Audit Packet Metadata

- Run ID: %d
- Packet ID: %s
- Generated: %s
- Decision: %s

## Scope Review

### Goal

%s

### Scope

%s

### Non-goals

%s

## Implementation Evidence

### Executor Result

**Source:** executor_result.txt

%s

## Validation Evidence

**Source:** %s

%s

## Changed Files / Diff Review

### Changed Files

%s

### Diff Preview

%s

## Warnings

%s

## Revision Requirements

%s

## Final Recommendation

**Decision:** %s

---

*This audit packet was generated by the Relay audit service. It does not constitute final human acceptance. A separate explicit approval action is required to accept or close the run.*
`

func GenerateAuditPacket(ev *Evidence, decision Decision) string {
	scopeGoal := ev.Packet.AuditSeed
	if scopeGoal == "" {
		scopeGoal = "_Not available — canonical_packet.json not found_"
	}

	execContent := "_Not available_"
	if ev.ExecutorResult.Present {
		execContent = ev.ExecutorResult.Content
	}

	valSource := "_Not available_"
	valContent := "_Not available_"
	if ev.ValidationOutput.Present {
		valSource = ev.ValidationOutput.Summary
		valContent = ev.ValidationOutput.Content
	}

	changedFiles := "_Not available_"
	if ev.ChangedFiles.Present {
		changedFiles = fmt.Sprintf("```\n%s\n```", ev.ChangedFiles.Preview)
	}

	diffPreview := "_Not available_"
	if ev.GitDiff.Present {
		diffPreview = fmt.Sprintf("```diff\n%s\n```", ev.GitDiff.Preview)
	}

	warningsText := "_None_"
	revisionText := "_None identified_"
	if len(ev.Warnings) > 0 {
		var wb strings.Builder
		for _, w := range ev.Warnings {
			wb.WriteString(fmt.Sprintf("- %s\n", w))
		}
		warningsText = wb.String()
		if decision == DecisionRevisionRequired || decision == DecisionBlocked {
			revisionText = warningsText
		}
	}

	return fmt.Sprintf(auditPacketTemplate,
		ev.RunID,
		ev.Packet.PacketID,
		time.Now().UTC().Format(time.RFC3339),
		string(decision),
		scopeGoal,
		scopeGoal,
		scopeGoal,
		execContent,
		valSource,
		valContent,
		changedFiles,
		diffPreview,
		warningsText,
		revisionText,
		string(decision),
	)
}

func DetermineDefaultDecision(ev *Evidence) Decision {
	if len(ev.Warnings) > 0 {
		return DecisionManualReviewRequired
	}
	return DecisionAccepted
}
