// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type PreviewDiffLine struct {
	Kind string
	Text string
}

type PreviewDiff struct {
	Lines     []PreviewDiffLine
	Truncated bool
}

type HandoffPreflightCheckView struct {
	Key     string
	Status  string
	Summary string
}

type OpenCodeTranscriptEventView struct {
	Kind string
	Text string
}

type ValidationProgressCommandView struct {
	Label      string
	Command    string
	Source     string
	Status     string
	ExitCode   int
	TimedOut   bool
	DurationMs int64
	HasStdout  bool
	HasStderr  bool
}

type ValidationProgressPreview struct {
	Status         string
	RepoPath       string
	StartedAt      string
	UpdatedAt      string
	FinishedAt     string
	CurrentIndex   int
	CurrentCommand string
	TotalCommands  int
	Commands       []ValidationProgressCommandView
	Error          string
}

type ValidationCommandPreview struct {
	Label      string
	Command    string
	Source     string
	ExitCode   int
	TimedOut   bool
	DurationMs int64
	HasStdout  bool
	HasStderr  bool
	Status     string
}

type ValidationRunPreview struct {
	Status          string
	RepoPath        string
	Commands        []ValidationCommandPreview
	CommandCount    int
	PassedCount     int
	FailedCount     int
	TimedOutCount   int
	TotalDurationMs int64
}

type WorkbenchNextActionView struct {
	Kind              string
	Title             string
	Summary           string
	Step              string
	PrimaryAction     string
	PrimaryFormAction string
	PrimaryHref       string
	Disabled          bool
	DisabledReason    string
	Severity          string
}

type RunPreviews struct {
	NextAction                  WorkbenchNextActionView
	OriginalHandoff             string
	ValidationJSON              string
	AgentPrompt                 string
	OpenCodePacket              string
	AgentPromptDiff             PreviewDiff
	AgentPromptEstimate         string
	HandoffPreflightStatus      string
	HandoffPreflightChecks      []HandoffPreflightCheckView
	OpenCodeCommandTemplate     string
	OpenCodeCommandPreview      string
	OpenCodeExecutionStatus     string
	OpenCodeExecutionExitCode   string
	OpenCodeExecutionStarted    string
	OpenCodeExecutionFinished   string
	OpenCodeRuntime             string
	OpenCodeLastOutputAt        string
	OpenCodeLastOutputAge       string
	OpenCodeLifecycleState      string
	OpenCodeStaleReason         string
	OpenCodeCanRecover          bool
	OpenCodeRecoveryActionLabel string
	OpenCodePermissionWarning   string
	OpenCodeStdoutArtifactID    int64
	OpenCodeStderrArtifactID    int64
	OpenCodeCombinedArtifactID  int64
	HasOpenCodeExecution        bool
	// OpenCode adapter fields
	OpenCodeBinary                  string
	OpenCodeArgs                    []string
	OpenCodeWorkDir                 string
	OpenCodeModel                   string
	OpenCodeAgent                   string
	OpenCodeVariant                 string
	OpenCodeThinking                string
	OpenCodeStdinSource             string
	OpenCodeStdinBytes              int
	OpenCodeAdapterError            string
	OpenCodeFailureHint             string
	OpenCodeExecutionError          string
	OpenCodeDryRunPreview           string
	HasOpenCodeDryRun               bool
	HasOpenCodeStdout               bool
	HasOpenCodeStderr               bool
	HasOpenCodeCombinedLog          bool
	ValidationRun                   ValidationRunPreview
	HasValidationCommands           bool
	HasOpenCodeCLICheck             bool
	OpenCodeCLICheckPreview         string
	OpenCodeCLICheckBinary          string
	OpenCodeCLICheckResolvedModel   string
	OpenCodeCLICheckModelAvailable  string
	OpenCodeCLICheckVersionExitCode string
	OpenCodeCLICheckModelsExitCode  string
	OpenCodeCLICheckCheckedAt       string
	OpenCodeCLICheckError           string
	OpenCodeCLICheckStatus          string

	IntakeRemediationHandoff    string
	HasIntakeRemediationHandoff bool

	// Agent Run Monitor fields
	HasOpenCodeRunning         bool
	HasOpenCodeStaleRunning    bool
	HasOpenCodeOutput          bool
	OpenCodeTranscript         []OpenCodeTranscriptEventView
	OpenCodeParsedResultStatus string
	OpenCodeParsedBuildStatus  string
	OpenCodeParsedTestStatus   string
	OpenCodeParsedLOCChanged   string
	OpenCodeParsedResultRaw    string
	OpenCodeStreamStdoutChunks int64
	OpenCodeStreamStderrChunks int64
	OpenCodeStreamStdoutBytes  int64
	OpenCodeStreamStderrBytes  int64
	OpenCodeStreamLastChunkAt  string
	OpenCodeStreamLastChunkAge string
	HasOpenCodeStreamActivity  bool

	HasValidationProgress     bool
	ValidationProgressRunning bool
	ValidationProgressStale   bool
	ValidationProgressPreview ValidationProgressPreview

	HasAuditHandoff bool
	AuditHandoff    string

	RepoPath               string
	SuggestedCommitMessage string

	HasCommitSuggestion         bool
	CommitMessage               string
	CommitSuggestionJSON        string
	CommitSuggestionStatus      string
	CommitSuggestionGeneratedAt string
	ValidationFailedAccepted    bool

	HasGitStatus        bool
	GitStatusPreview    string
	HasGitDiffStat      bool
	GitDiffStatPreview  string
	HasGitDiffPatch     bool
	GitDiffPatchPreview string
	GitChangedFileCount int64
	GitDiffSummary      string
}

func RunPreviewPanels(previews RunPreviews) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"grid grid-cols-1 gap-4 p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = previewPanel("Original Handoff", "original-handoff-preview", previews.OriginalHandoff, "No original handoff artifact found yet.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = previewPanel("Validation Report", "validation-report-preview", previews.ValidationJSON, "No validation report generated yet.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = previewPanel("Agent Prompt", "agent-prompt-preview", previews.AgentPrompt, "No agent prompt generated yet.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func previewPanel(title string, id string, content string, emptyText string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<section class=\"relay-card min-w-0\"><div class=\"flex items-center justify-between border-b border-gray-800 px-4 py-3\"><h3 class=\"font-medium text-sm sm:text-base\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/run_previews.templ`, Line: 204, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if content != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<button type=\"button\" data-copy-target=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(id)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/run_previews.templ`, Line: 207, Col: 26}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"text-xs text-indigo-400 hover:text-indigo-300 min-h-[36px] inline-flex items-center\">Copy</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if content == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<p class=\"p-4 text-xs text-gray-600\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(emptyText)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/run_previews.templ`, Line: 214, Col: 51}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"p-4 max-h-80 overflow-y-auto overflow-x-auto min-w-0\"><pre id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(id)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/run_previews.templ`, Line: 217, Col: 16}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" class=\"text-xs font-mono text-gray-300 whitespace-pre-wrap break-words\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(content)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/run_previews.templ`, Line: 217, Col: 100}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</pre></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
